// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         group_id: "grp_abc123def456"
 *     }
 */
export interface GetGroupsRequest {
    /** Unique group identifier (grp_*) */
    group_id: VitableConnect.GroupId;
}
