configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/vitable%2Fvitable-connect-96179d55665afbff5aca73845920de0597dfcc151a97fabf93a4cc818d7859eb.yml
openapi_spec_hash: 4eb9796fe4adb7074b6df7ffdc6caa8d
config_hash: d2ce0848d5b4f2e1461c01f6eafd9b19
