// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         member_id: "mbr_abc123def456",
 *         first_name: "Sam",
 *         last_name: "Doe",
 *         date_of_birth: "2015-06-01",
 *         sex_at_birth: "Male",
 *         relationship: "Child",
 *         address: {
 *             address_line_1: "123 Main St",
 *             city: "Detroit",
 *             state: "MI",
 *             zipcode: "48201"
 *         }
 *     }
 */
export interface CreateMemberDependentRequest {
    /** Unique member identifier (mbr_*) */
    member_id: VitableConnect.MemberId;
    /** Organization to act as for this request (e.g. `org_SGVsbG8gV29ybGQ`). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 `organization_required`. A malformed value returns 400 `invalid_organization_header`, and naming an organization you do not have access to returns 403 `organization_access_denied`. */
    "X-Vitable-Organization"?: VitableConnect.XVitableOrganization;
    /** Dependent's legal first name */
    first_name: string;
    /** Dependent's legal last name */
    last_name: string;
    /**
     * Name suffix
     *
     * * `Sr` - Sr
     * * `Jr` - Jr
     * * `I` - I
     * * `II` - II
     * * `III` - III
     * * `IV` - IV
     * * `V` - V
     */
    suffix?: VitableConnect.NameSuffix | null;
    /** Date of birth (YYYY-MM-DD); cannot be in the future */
    date_of_birth: string;
    /**
     * Sex assigned at birth
     *
     * * `Male` - Male
     * * `Female` - Female
     * * `Other` - Other
     * * `Unknown` - Unknown
     */
    sex_at_birth?: VitableConnect.SexAtBirth | null;
    /**
     * Gender identity
     *
     * * `Male` - Male
     * * `Female` - Female
     * * `Transgender` - Transgender
     * * `Non-binary` - Non-binary
     * * `Prefer not to respond` - Prefer not to respond
     */
    gender?: VitableConnect.Gender | null;
    /** Dependent's email address. Ignored for dependents under 18, and not changed for a dependent Vitable already has on file. */
    email?: string | null;
    /** Dependent's 10-digit US phone number; formatting characters and a leading 1 are ignored. Ignored for dependents under 18, and not changed for a dependent Vitable already has on file. */
    phone?: string | null;
    /**
     * Relationship of the dependent to the member
     *
     * * `Spouse` - Spouse
     * * `Child` - Child
     */
    relationship: VitableConnect.Relationship;
    /** Dependent's residential address */
    address: VitableConnect.CreateMemberDependentAddressRequest;
}
