// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         member_id: "mbr_abc123def456"
 *     }
 */
export interface GetMembersRequest {
    /** Unique member identifier (mbr_*) */
    member_id: VitableConnect.MemberId;
}
