// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListMembersRequest {
    /** Items per page (default: 20, max: 100) */
    limit?: VitableConnect.Limit;
    /** Page number (default: 1) */
    page?: VitableConnect.Page;
    /** Case-insensitive search across member name, email, and phone number; exact match on member id (prefixed or raw uuid) */
    search?: VitableConnect.MemberSearch;
    /** Organization to act as for this request (e.g. `org_SGVsbG8gV29ybGQ`). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 `organization_required`. A malformed value returns 400 `invalid_organization_header`, and naming an organization you do not have access to returns 403 `organization_access_denied`. */
    "X-Vitable-Organization"?: VitableConnect.XVitableOrganization;
}
