// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         member_id: "mbr_abc123def456",
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListQualifyingLifeEventsMembersRequest {
    /** Unique member identifier (mbr_*) */
    member_id: VitableConnect.MemberId;
    /** Items per page (default: 20, max: 100) */
    limit?: VitableConnect.Limit;
    /** Page number (default: 1) */
    page?: VitableConnect.Page;
    /** Optional. Filter to a single QLE status; omit to return all statuses. */
    status?: VitableConnect.Status;
}
