// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListMembersRequest {
    /** Items per page (default: 20, max: 100) */
    limit?: VitableConnect.Limit;
    /** Page number (default: 1) */
    page?: VitableConnect.Page;
    /** Case-insensitive search across member name, email, and phone number; exact match on member id (prefixed or raw uuid) */
    search?: VitableConnect.MemberSearch;
}
