// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         group_id: "grp_abc123def456",
 *         members: [{
 *                 reference_id: "EMP-001",
 *                 first_name: "Jane",
 *                 last_name: "Doe",
 *                 date_of_birth: "1990-05-15",
 *                 phone: "4155550100",
 *                 plan_id: "pln_abc123def456",
 *                 address: {
 *                     address_line_1: "123 Main Street",
 *                     address_line_2: "Apt 4B",
 *                     city: "San Francisco",
 *                     state: "CA",
 *                     zipcode: "94102"
 *                 },
 *                 email: "jane.doe@acme.com"
 *             }]
 *     }
 */
export interface GroupMemberSyncRequest {
    group_id: VitableConnect.GroupId;
    members: VitableConnect.GroupMemberSyncMemberRequest[];
}
