// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         employees: [{
 *                 reference_id: "EMP-001",
 *                 first_name: "Jane",
 *                 last_name: "Doe",
 *                 date_of_birth: "1990-05-15",
 *                 email: "jane.doe@acme.com",
 *                 phone: "4155550100",
 *                 address: {
 *                     address_line_1: "123 Main Street",
 *                     address_line_2: "Apt 4B",
 *                     city: "San Francisco",
 *                     state: "CA",
 *                     zipcode: "94102"
 *                 },
 *                 start_date: "2024-01-15",
 *                 employee_class: "Full Time",
 *                 compensation_type: "Salary"
 *             }, {
 *                 first_name: "John",
 *                 last_name: "Smith",
 *                 date_of_birth: "1985-11-20",
 *                 email: "john.smith@acme.com",
 *                 phone: "4155550101",
 *                 start_date: "2024-03-01",
 *                 employee_class: "Part Time",
 *                 compensation_type: "Hourly"
 *             }]
 *     }
 */
export interface CensusSyncRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    employees: VitableConnect.CensusSyncEmployeeRequest[];
}
