// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "NewCo Industries",
 *         legal_name: "NewCo Industries LLC",
 *         ein: "12-3456789",
 *         email: "hr@newco.com",
 *         address: {
 *             address_line_1: "789 Business Blvd",
 *             address_line_2: "Floor 5",
 *             city: "Seattle",
 *             state: "WA",
 *             zipcode: "98101"
 *         },
 *         phone_number: "2065550100",
 *         reference_id: "partner-emp-001"
 *     }
 */
export interface CreateEmployerRequest {
    /** Employer display name */
    name: string;
    /** Legal business name */
    legal_name: string;
    /** Employer Identification Number (format: XX-XXXXXXX) */
    ein: string;
    /** Email address for billing and communications */
    email: string;
    /** Employer address */
    address: VitableConnect.EmployerAddressInput;
    /** Employer phone number (10-digit US format, e.g. 5551234567) */
    phone_number?: string | null;
    /** External reference ID for this employer */
    reference_id?: string | null;
}
