// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         invoice_id: "INV-00042"
 *     }
 */
export interface GetInvoicePdfEmployersRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** External Chargebee invoice id (not a prefixed UUID). */
    invoice_id: VitableConnect.InvoiceId;
}
