// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListPayrollDeductionStatementsEmployersRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** Maximum number of statements per page */
    limit?: VitableConnect.Limit;
    /** Page number to retrieve (starts at 1) */
    page?: VitableConnect.Page;
}
