// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         limit: 20
 *     }
 */
export interface ListInvoicesEmployersRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** Maximum number of invoices per page */
    limit?: VitableConnect.Limit;
    /** Opaque cursor from a previous page's next_offset */
    offset?: VitableConnect.Offset | null;
}
