// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListEmployersRequest {
    /** Filter to employers with at least one active benefit in these families. */
    benefit_family?: VitableConnect.BenefitFamilyParamItem | VitableConnect.BenefitFamilyParamItem[];
    /** Filter to employers in one of these computed benefit-lifecycle stages. */
    benefit_lifecycle_stage?: VitableConnect.BenefitLifecycleStageItem | VitableConnect.BenefitLifecycleStageItem[];
    /** Filter to employers whose HRIS connection is with one of these payroll providers (e.g. `ADP RUN`). Matched case-insensitively; free text, so read the available values from the HRIS-providers endpoint rather than assuming a fixed set. */
    hris_provider?: string | string[];
    /** Filter to employers whose HRIS connection is in one of these statuses. */
    hris_status?: VitableConnect.HrisStatusItem | VitableConnect.HrisStatusItem[];
    /** Include cancelled employers (hidden by default unless their stage is explicitly requested). */
    include_cancelled?: VitableConnect.IncludeCancelled;
    /** Items per page. */
    limit?: VitableConnect.Limit;
    /** Page number. */
    page?: VitableConnect.Page;
    /** Employer filter. Matches the display name or the legal name case-insensitively as a substring, or one of these exactly: the EIN (with or without its dash), the employer id, or the contact email of one of the employer's non-disabled admins. */
    search?: VitableConnect.Search | null;
}
