// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListPayrollDeductionStatementsEmployersRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** Maximum number of statements per page */
    limit?: VitableConnect.Limit;
    /** Page number to retrieve (starts at 1) */
    page?: VitableConnect.Page;
    /** Organization to act as for this request (e.g. `org_SGVsbG8gV29ybGQ`). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 `organization_required`. A malformed value returns 400 `invalid_organization_header`, and naming an organization you do not have access to returns 403 `organization_access_denied`. */
    "X-Vitable-Organization"?: VitableConnect.XVitableOrganization;
}
