// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         limit: 20,
 *         page: 1,
 *         search: "jane"
 *     }
 */
export interface ListEmployeesEmployersRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** Filter by employment status (active or terminated) */
    employment_status?: VitableConnect.EmployeeStatus;
    /** Items per page (default: 20, max: 100) */
    limit?: VitableConnect.Limit;
    /** Page number (default: 1) */
    page?: VitableConnect.Page;
    /** Case-insensitive search across employee first name, last name, and email */
    search?: VitableConnect.EmployeeSearch;
}
