// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456",
 *         employees_in_payroll_acknowledged: true,
 *         payroll_data_impacts_eligibility_acknowledged: true,
 *         classifications_accurate: true,
 *         all_benefit_eligible_employees_present: true,
 *         is_controlled_group: true,
 *         access_method: "SELF_SETUP",
 *         has_additional_payroll_system: true
 *     }
 */
export interface SubmitPayrollAccessSetupRequest {
    employer_id: VitableConnect.EmployerId;
    /** Organization to act as for this request (e.g. `org_SGVsbG8gV29ybGQ`). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 `organization_required`. A malformed value returns 400 `invalid_organization_header`, and naming an organization you do not have access to returns 403 `organization_access_denied`. */
    "X-Vitable-Organization"?: VitableConnect.XVitableOrganization;
    /** Attestation that all benefit-eligible employees appear in the payroll system. */
    employees_in_payroll_acknowledged: boolean;
    /** Attestation that changes to payroll data affect benefit eligibility. */
    payroll_data_impacts_eligibility_acknowledged: boolean;
    /** Attestation that employee classifications in payroll are accurate. Set `false` to report corrections in the fields below. */
    classifications_accurate: boolean;
    /** Where corrected classifications come from, when `classifications_accurate` is `false`. */
    classification_correction_source?: VitableConnect.ClassificationCorrectionSource | null;
    /** Names of employees whose payroll classification needs correcting. */
    misclassified_employee_names?: string[];
    /** How to handle employees still missing from the payroll system. */
    remaining_employee_action?: VitableConnect.RemainingEmployeeAction | null;
    /** Attestation that every benefit-eligible employee is present in payroll. */
    all_benefit_eligible_employees_present: boolean;
    /** How any missing employees will be added, when some are absent. */
    missing_employee_resolution?: VitableConnect.MissingEmployeeResolution | null;
    /** Whether this employer belongs to a controlled group of related entities. */
    is_controlled_group: boolean;
    /** Whether this payroll system also covers other EINs in the controlled group. */
    same_payroll_covers_other_eins?: boolean | null;
    access_method: VitableConnect.AccessMethod;
    /** Sign-in URL for the payroll system. */
    login_url?: string | null;
    /** Username Vitable should use to access the payroll system. */
    username?: string | null;
    /** Phone number used for payroll-system verification codes. */
    phone?: string | null;
    /** Password Vitable should use to access the payroll system. */
    password?: string | null;
    /** Whether the payroll integration has been confirmed as working. */
    integration_confirmed?: boolean | null;
    /** Whether a second payroll system is in use. When `true`, supply the `additional_*` fields below. */
    has_additional_payroll_system: boolean;
    /** How Vitable will access the second payroll system. */
    additional_access_method?: VitableConnect.AdditionalAccessMethod | null;
    /** Sign-in URL for the second payroll system. */
    additional_login_url?: string | null;
    /** Username Vitable should use for the second payroll system. */
    additional_username?: string | null;
    /** Phone number used for second payroll-system verification codes. */
    additional_phone?: string | null;
    /** Password Vitable should use for the second payroll system. */
    additional_password?: string | null;
    /** Whether the second payroll integration has been confirmed as working. */
    additional_integration_confirmed?: boolean | null;
}
