// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employer_id: "empr_abc123def456"
 *     }
 */
export interface UpdateEmployerRequest {
    /** Unique employer identifier (empr_*) */
    employer_id: VitableConnect.EmployerId;
    /** Employer display name */
    name?: string | null;
    /** Legal business name */
    legal_name?: string | null;
    /** Employer address */
    address?: VitableConnect.UpdateEmployerAddressInput | null;
    /** Whether the employer is active */
    active?: boolean | null;
}
