// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         enrollment_id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ"
 *     }
 */
export interface GetEnrollmentsRequest {
    /** Unique enrollment identifier (enrl_*) */
    enrollment_id: VitableConnect.EnrollmentId;
}
