// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         enrollment_id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ",
 *         reason: "Member needs a new election after a qualifying event.",
 *         ticket_number: "BPT-1234",
 *         qualifying_life_event_id: "qle_AAAAAAAAAAAAAAAAAAAAAQ"
 *     }
 *
 * @example
 *     {
 *         enrollment_id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ",
 *         reason: "Member needs a new election."
 *     }
 */
export interface ReissueEnrollmentRequest {
    /** Unique enrollment identifier (enrl_*) */
    enrollment_id: VitableConnect.EnrollmentId;
    /** Audit reason for the reissue; required for user-backed callers and optional for long-lived organization API-key callers */
    reason?: string | null;
    /** Optional support or operational ticket number */
    ticket_number?: string | null;
    /** Accepted member qualifying life event identifier (qle_*) */
    qualifying_life_event_id?: string | null;
}
