// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         enrollment_id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ",
 *         reason: "Member requested coverage termination after a qualifying event.",
 *         ticket_number: "BPT-1234",
 *         qualifying_life_event_id: "qle_AAAAAAAAAAAAAAAAAAAAAQ"
 *     }
 *
 * @example
 *     {
 *         enrollment_id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ",
 *         reason: "Member requested coverage termination."
 *     }
 */
export interface TerminateEnrollmentRequest {
    /** Unique enrollment identifier (enrl_*) */
    enrollment_id: VitableConnect.EnrollmentId;
    /** Organization to act as for this request (e.g. `org_SGVsbG8gV29ybGQ`). Optional when your credentials reach a single organization. Required when they reach several — omitting it then returns 400 `organization_required`. A malformed value returns 400 `invalid_organization_header`, and naming an organization you do not have access to returns 403 `organization_access_denied`. */
    "X-Vitable-Organization"?: VitableConnect.XVitableOrganization;
    /** Audit reason for the termination; required for user-backed callers and optional for long-lived organization API-key callers */
    reason?: string | null;
    /** Optional support or operational ticket number */
    ticket_number?: string | null;
    /** Accepted member qualifying life event identifier (qle_*) */
    qualifying_life_event_id?: string | null;
}
