// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as VitableConnect from "../../../index.js";

export declare namespace WebhookEventsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Inspect the events Vitable emits for your organization and the delivery attempts for each one. Rather than polling the API for changes, register a webhook endpoint and Vitable will `POST` event data to your URL as things happen.
 */
export class WebhookEventsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhookEventsClient.Options>;

    constructor(options: WebhookEventsClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves a paginated list of webhook events for the authenticated organization. Supports filtering by event name, resource type, resource ID, and date range.
     *
     * @param {VitableConnect.ListWebhookEventsRequest} request
     * @param {WebhookEventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link VitableConnect.BadRequestError}
     * @throws {@link VitableConnect.UnauthorizedError}
     * @throws {@link VitableConnect.ForbiddenError}
     * @throws {@link VitableConnect.NotFoundError}
     * @throws {@link VitableConnect.ConflictError}
     * @throws {@link VitableConnect.TooManyRequestsError}
     * @throws {@link VitableConnect.InternalServerError}
     * @throws {@link VitableConnect.BadGatewayError}
     * @throws {@link errors.VitableConnectError}
     * @throws {@link errors.VitableConnectTimeoutError}
     *
     * @example
     *     await client.webhookEvents.list({
     *         limit: 20,
     *         page: 1
     *     })
     */
    public async list(
        request: VitableConnect.ListWebhookEventsRequest = {},
        requestOptions?: WebhookEventsClient.RequestOptions,
    ): Promise<core.Page<VitableConnect.WebhookEvent, VitableConnect.WebhookEventListResponse>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: VitableConnect.ListWebhookEventsRequest,
            ): Promise<core.WithRawResponse<VitableConnect.WebhookEventListResponse>> => {
                const {
                    created_after: createdAfter,
                    created_before: createdBefore,
                    event_name: eventName,
                    limit,
                    page,
                    resource_id: resourceId,
                    resource_type: resourceType,
                } = request;
                const _queryParams: Record<string, unknown> = {
                    created_after: createdAfter != null ? createdAfter : undefined,
                    created_before: createdBefore != null ? createdBefore : undefined,
                    event_name: eventName != null ? eventName : undefined,
                    limit,
                    page,
                    resource_id: resourceId,
                    resource_type: resourceType != null ? resourceType : undefined,
                };
                const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
                const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
                    _authRequest.headers,
                    this._options?.headers,
                    requestOptions?.headers,
                );
                const _response = await (this._options.fetcher ?? core.fetcher)({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.VitableConnectEnvironment.Production,
                        "v1/webhook-events",
                    ),
                    method: "GET",
                    headers: _headers,
                    queryString: core.url
                        .queryBuilder()
                        .addMany(_queryParams)
                        .mergeAdditional(requestOptions?.queryParams)
                        .build(),
                    timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
                    maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                    fetchFn: this._options?.fetch,
                    logging: this._options.logging,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as VitableConnect.WebhookEventListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    switch (_response.error.statusCode) {
                        case 400:
                            throw new VitableConnect.BadRequestError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 401:
                            throw new VitableConnect.UnauthorizedError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 403:
                            throw new VitableConnect.ForbiddenError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 404:
                            throw new VitableConnect.NotFoundError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 409:
                            throw new VitableConnect.ConflictError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 429:
                            throw new VitableConnect.TooManyRequestsError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 500:
                            throw new VitableConnect.InternalServerError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        case 502:
                            throw new VitableConnect.BadGatewayError(
                                _response.error.body as VitableConnect.ErrorResponse,
                                _response.rawResponse,
                            );
                        default:
                            throw new errors.VitableConnectError({
                                statusCode: _response.error.statusCode,
                                body: _response.error.body,
                                rawResponse: _response.rawResponse,
                            });
                    }
                }
                return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/webhook-events");
            },
        );
        let _offset = request?.page != null ? request?.page : 1;
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Page<VitableConnect.WebhookEvent, VitableConnect.WebhookEventListResponse>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) => (response?.data ?? []).length > 0,
            getItems: (response) => response?.data ?? [],
            loadPage: (_response) => {
                _offset += 1;
                return list(core.setObjectProperty(request, "page", _offset));
            },
        });
    }

    /**
     * Retrieves a single webhook event by its prefixed ID. Returns 404 if the event does not exist or belongs to a different organization.
     *
     * @param {VitableConnect.GetWebhookEventsRequest} request
     * @param {WebhookEventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link VitableConnect.BadRequestError}
     * @throws {@link VitableConnect.UnauthorizedError}
     * @throws {@link VitableConnect.ForbiddenError}
     * @throws {@link VitableConnect.NotFoundError}
     * @throws {@link VitableConnect.ConflictError}
     * @throws {@link VitableConnect.TooManyRequestsError}
     * @throws {@link VitableConnect.InternalServerError}
     * @throws {@link VitableConnect.BadGatewayError}
     * @throws {@link errors.VitableConnectError}
     * @throws {@link errors.VitableConnectTimeoutError}
     *
     * @example
     *     await client.webhookEvents.get({
     *         event_id: "event_id"
     *     })
     */
    public get(
        request: VitableConnect.GetWebhookEventsRequest,
        requestOptions?: WebhookEventsClient.RequestOptions,
    ): core.HttpResponsePromise<VitableConnect.WebhookEventResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: VitableConnect.GetWebhookEventsRequest,
        requestOptions?: WebhookEventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VitableConnect.WebhookEventResponse>> {
        const { event_id: eventId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VitableConnectEnvironment.Production,
                `v1/webhook-events/${core.url.encodePathParam(eventId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as VitableConnect.WebhookEventResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new VitableConnect.BadRequestError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new VitableConnect.UnauthorizedError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new VitableConnect.ForbiddenError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new VitableConnect.NotFoundError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new VitableConnect.ConflictError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new VitableConnect.TooManyRequestsError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new VitableConnect.InternalServerError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 502:
                    throw new VitableConnect.BadGatewayError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.VitableConnectError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/webhook-events/{event_id}");
    }

    /**
     * Retrieves all delivery attempts for a webhook event. Returns up to 100 deliveries. Each delivery includes a computed status field (Pending, In Progress, Delivered, or Failed).
     *
     * @param {VitableConnect.ListDeliveriesWebhookEventsRequest} request
     * @param {WebhookEventsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link VitableConnect.BadRequestError}
     * @throws {@link VitableConnect.UnauthorizedError}
     * @throws {@link VitableConnect.ForbiddenError}
     * @throws {@link VitableConnect.NotFoundError}
     * @throws {@link VitableConnect.ConflictError}
     * @throws {@link VitableConnect.TooManyRequestsError}
     * @throws {@link VitableConnect.InternalServerError}
     * @throws {@link VitableConnect.BadGatewayError}
     * @throws {@link errors.VitableConnectError}
     * @throws {@link errors.VitableConnectTimeoutError}
     *
     * @example
     *     await client.webhookEvents.listDeliveries({
     *         event_id: "event_id"
     *     })
     */
    public listDeliveries(
        request: VitableConnect.ListDeliveriesWebhookEventsRequest,
        requestOptions?: WebhookEventsClient.RequestOptions,
    ): core.HttpResponsePromise<VitableConnect.ListWebhookEventDeliveriesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDeliveries(request, requestOptions));
    }

    private async __listDeliveries(
        request: VitableConnect.ListDeliveriesWebhookEventsRequest,
        requestOptions?: WebhookEventsClient.RequestOptions,
    ): Promise<core.WithRawResponse<VitableConnect.ListWebhookEventDeliveriesResponse>> {
        const { event_id: eventId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VitableConnectEnvironment.Production,
                `v1/webhook-events/${core.url.encodePathParam(eventId)}/deliveries`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as VitableConnect.ListWebhookEventDeliveriesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new VitableConnect.BadRequestError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new VitableConnect.UnauthorizedError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new VitableConnect.ForbiddenError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new VitableConnect.NotFoundError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new VitableConnect.ConflictError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new VitableConnect.TooManyRequestsError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new VitableConnect.InternalServerError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                case 502:
                    throw new VitableConnect.BadGatewayError(
                        _response.error.body as VitableConnect.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.VitableConnectError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/webhook-events/{event_id}/deliveries",
        );
    }
}
