// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employee_id: "empl_abc123def456"
 *     }
 */
export interface GetEmployeesRequest {
    /** Unique employee identifier (empl_*) */
    employee_id: VitableConnect.EmployeeId;
}
