// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         employee_id: "empl_abc123def456",
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListEnrollmentsEmployeesRequest {
    /** Unique employee identifier (empl_*) */
    employee_id: VitableConnect.EmployeeId;
    /** Items per page (default: 20, max: 100) */
    limit?: VitableConnect.Limit;
    /** Page number (default: 1) */
    page?: VitableConnect.Page;
}
