// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         grant_type: "client_credentials"
 *     }
 *
 * @example
 *     {
 *         grant_type: "client_credentials",
 *         bound_entity: {
 *             id: "empr_SGVsbG8gV29ybGQ",
 *             type: "employer"
 *         }
 *     }
 */
export interface IssueAccessTokenRequest {
    /**
     * Token issuance flow. Currently only 'client_credentials' supported.
     *
     * * `client_credentials` - client_credentials
     */
    grant_type: VitableConnect.GrantType;
    /** Optional entity to bind the token to for scoped access */
    bound_entity?: VitableConnect.BoundEntity | null;
}
