// This file was auto-generated by Fern from our API Definition.

/**
 * * `SELF_SETUP` - SELF_SETUP
 * * `NEEDS_HELP` - NEEDS_HELP
 */
export const AccessMethod = {
    SelfSetup: "SELF_SETUP",
    NeedsHelp: "NEEDS_HELP",
} as const;
export type AccessMethod = (typeof AccessMethod)[keyof typeof AccessMethod];
