// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface AccessTokenResponse {
    /** The issued access token (vit_at_*) */
    access_token: string;
    /** Token type, always 'Bearer' */
    token_type: string;
    /** Token lifetime in seconds */
    expires_in: number;
    /** Entity the token is bound to, if any */
    bound_entity?: (VitableConnect.BoundEntityResponse | null) | undefined;
}
