// This file was auto-generated by Fern from our API Definition.

export interface AddressRequest {
    /** Street address, including house or building number. */
    address_line_1: string;
    /** Apartment, suite, unit, or floor. Omit if not applicable. */
    address_line_2?: (string | null) | undefined;
    /** City or town name. */
    city: string;
    /** Two-letter USPS state or territory code, e.g. `PA`. */
    state: string;
    /** US postal code, either five digits or ZIP+4. */
    zipcode: string;
}
