// This file was auto-generated by Fern from our API Definition.

/**
 * * `mec` - Mec
 * * `mvp` - Mvp
 * * `ichra` - Ichra
 * * `vpc` - Vpc
 * * `dental` - Dental
 * * `vision` - Vision
 */
export const BenefitFamily = {
    Mec: "mec",
    Mvp: "mvp",
    Ichra: "ichra",
    Vpc: "vpc",
    Dental: "dental",
    Vision: "vision",
} as const;
export type BenefitFamily = (typeof BenefitFamily)[keyof typeof BenefitFamily];
