// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * One plan year, detail view.
 *
 * Standalone (no shared base) so the exact detail payload is readable in one place; the list
 * serializer is a separate class even where fields overlap. Detail carries the SPD link and omits
 * the list-only ``is_current`` flag.
 */
export interface BenefitPlanYearDetail {
    /** Prefixed plan-year identifier (`plyr_*`). */
    benefit_plan_year_id: string;
    /** Prefixed benefit identifier (`bprd_*`). */
    benefit_id: string;
    /** Calendar coverage year. */
    year: number;
    /**
     * Benefit family.
     *
     * * `mec` - Mec
     * * `mvp` - Mvp
     * * `ichra` - Ichra
     * * `vpc` - Vpc
     * * `dental` - Dental
     * * `vision` - Vision
     */
    family: VitableConnect.BenefitFamily;
    /** Benefit/product display name. */
    product_name: string;
    /** Carrier name, or null (e.g. ICHRA). */
    carrier: string | null;
    /** Displayed networks: ["multi"] for ICHRA, otherwise the plan year's distinct network names. */
    network_names: string[];
    /** Monthly premium in cents; only for an ICHRA benefit with effective coverage. */
    premium_in_cents: number | null;
    /** Employee contribution range. */
    employee_contribution: VitableConnect.ContributionRange | null;
    /** Employer contribution range. */
    employer_contribution: VitableConnect.ContributionRange | null;
    /**
     * `active`/`upcoming`/`inactive`.
     *
     * * `active` - Active
     * * `upcoming` - Upcoming
     * * `open_enrollment` - Open Enrollment
     * * `inactive` - Inactive
     */
    status: VitableConnect.BenefitStatus;
    /** Coverage start. */
    coverage_start: string;
    /** Coverage end. */
    coverage_end: string | null;
    /** Open-enrollment start. */
    open_enrollment_start: string;
    /** Open-enrollment end. */
    open_enrollment_end: string | null;
    /** Distinct offered state codes. */
    offered_states: string[];
    /** Enrolled/eligible rate for this plan year. */
    enrollment_rate: VitableConnect.EnrollmentRate;
    /** Summary Plan Description (SPD) link, or null. */
    spd_file_url: string | null;
    /** How the plan year prices contributions (ICHRA classes or coverage tiers). */
    contribution_strategy: VitableConnect.ContributionStrategy;
    /** The plan year's active eligibility policy, or null. */
    eligibility_policy: VitableConnect.EligibilityPolicy | null;
}
