// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface BenefitSummary {
    /** Benefit product ID (bprd_*) */
    id: string;
    /** Display name of the benefit product */
    name: string;
    /**
     * Programmatic product identifier
     *
     * * `EBA` - Eba Mec
     * * `VPC` - Vpc Enhanced
     * * `VPC_CORE` - Vpc Core
     * * `MEC` - Vpc Mec
     * * `MEC2` - Mec2
     * * `MEC_PLUS` - Mec Plus
     * * `MVP` - Mvp
     * * `MVP2` - Mvp2
     * * `MVPSL` - Mvpsl
     * * `MVPSL2` - Mvpsl2
     * * `VD` - Dental
     * * `VV` - Vision
     * * `ICHRA` - Ichra
     * * `ICHRA_PREMIUM_PLUS` - Ichra Premium Plus
     * * `ICHRA_REIMBURSEMENT_ONLY` - Ichra Reimbursement Only
     */
    product_code: VitableConnect.ProductCode;
    /**
     * High-level benefit grouping
     *
     * * `Medical` - Medical
     * * `Dental` - Dental
     * * `Vision` - Vision
     * * `Hospital` - Hospital
     */
    category: VitableConnect.Category;
}
