// This file was auto-generated by Fern from our API Definition.

/**
 * * `open_enrollment` - open_enrollment
 * * `renewal` - renewal
 * * `active` - active
 * * `onboarding` - onboarding
 * * `cancelled` - cancelled
 */
export const BenefitLifecycleStageItem = {
    OpenEnrollment: "open_enrollment",
    Renewal: "renewal",
    Active: "active",
    Onboarding: "onboarding",
    Cancelled: "cancelled",
} as const;
export type BenefitLifecycleStageItem = (typeof BenefitLifecycleStageItem)[keyof typeof BenefitLifecycleStageItem];
