// This file was auto-generated by Fern from our API Definition.

/**
 * * `active` - Active
 * * `upcoming` - Upcoming
 * * `open_enrollment` - Open Enrollment
 * * `inactive` - Inactive
 */
export const BenefitStatus = {
    Active: "active",
    Upcoming: "upcoming",
    OpenEnrollment: "open_enrollment",
    Inactive: "inactive",
} as const;
export type BenefitStatus = (typeof BenefitStatus)[keyof typeof BenefitStatus];
