// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface BenefitPlanNetwork {
    /** Unique identifier for the network. */
    id?: string | undefined;
    /** Name of the network */
    name: string;
    /** URL of the network's logo, or `null` if none is on file. */
    logo: string | null;
    /** Postal address of the provider network. */
    address: VitableConnect.Address;
    /** Network's EDI */
    edi?: (string | null) | undefined;
    /** Website of the network */
    website: string;
    /** General contact phone number for the network. */
    phone: string;
    /** Website for members */
    member_website?: (string | null) | undefined;
    /** Phone number members should call for support. */
    member_phone: string | null;
    /** Website for providers */
    provider_website?: (string | null) | undefined;
    /** Phone number providers should call for claims and eligibility. */
    provider_phone: string | null;
}
