// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface BoundEntityResponse {
    /** Prefixed entity ID the token is bound to (empr_* or empl_*) */
    id: string;
    /**
     * Type of bound entity
     *
     * * `employer` - employer
     * * `employee` - employee
     */
    type: VitableConnect.BoundEntityType;
}
