// This file was auto-generated by Fern from our API Definition.

/**
 * * `employer` - employer
 * * `employee` - employee
 */
export const BoundEntityType = {
    Employer: "employer",
    Employee: "employee",
} as const;
export type BoundEntityType = (typeof BoundEntityType)[keyof typeof BoundEntityType];
