// This file was auto-generated by Fern from our API Definition.

/**
 * * `medical` - medical
 * * `dental` - dental
 * * `vision` - vision
 * * `rx` - rx
 */
export const CardType = {
    Medical: "medical",
    Dental: "dental",
    Vision: "vision",
    Rx: "rx",
} as const;
export type CardType = (typeof CardType)[keyof typeof CardType];
