// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single census sync detail resource.
 */
export interface CensusSyncDetailResponse {
    /** The census sync request, including its current processing status. */
    data: VitableConnect.CensusSyncResponse;
}
