// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface CensusSyncEmployeeRequest {
    /** Your own identifier for this employee. Vitable echoes it back on sync results so you can match failures to your records. */
    reference_id?: (string | null) | undefined;
    /** Employee's legal first name. */
    first_name: string;
    /** Employee's legal last name. */
    last_name: string;
    /** Employee's date of birth as `YYYY-MM-DD`. Used to match existing members. */
    date_of_birth: string;
    /** Employee's work email address. Vitable sends enrollment invitations here. */
    email: string;
    /** Phone number */
    phone?: (string | null) | undefined;
    /** Employee's home address, used to determine plan availability. */
    address?: (VitableConnect.CensusSyncEmployeeAddressRequest | null) | undefined;
    /** Employment start date as `YYYY-MM-DD`. Drives benefit eligibility dates. */
    start_date?: (string | null) | undefined;
    /** Employee class used to match the employer's eligibility policy rules. */
    employee_class?: (VitableConnect.EmployeeClass | null) | undefined;
    /** Whether the employee is salaried or hourly. */
    compensation_type?: (VitableConnect.CompensationType | null) | undefined;
}
