// This file was auto-generated by Fern from our API Definition.

/**
 * * `ENTER_NAMES` - ENTER_NAMES
 * * `EMAIL_LIST` - EMAIL_LIST
 */
export const ClassificationCorrectionSource = {
    EnterNames: "ENTER_NAMES",
    EmailList: "EMAIL_LIST",
} as const;
export type ClassificationCorrectionSource =
    (typeof ClassificationCorrectionSource)[keyof typeof ClassificationCorrectionSource];
