// This file was auto-generated by Fern from our API Definition.

/**
 * * `Salary` - Salary
 * * `Hourly` - Hourly
 */
export const CompensationType = {
    Salary: "Salary",
    Hourly: "Hourly",
} as const;
export type CompensationType = (typeof CompensationType)[keyof typeof CompensationType];
