// This file was auto-generated by Fern from our API Definition.

/**
 * * `Unspecified` - Unspecified
 * * `Salary` - Salary
 * * `Hourly` - Hourly
 */
export const ContributionClassCompensation = {
    Unspecified: "Unspecified",
    Salary: "Salary",
    Hourly: "Hourly",
} as const;
export type ContributionClassCompensation =
    (typeof ContributionClassCompensation)[keyof typeof ContributionClassCompensation];
