// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * One non-ICHRA coverage tier, mirroring the internal configuration ``CompanyBenefitPlanTierCostDTO``
 * minus the tier-cost id, ``pepm`` and ``pepm_per_dependent``; ``benefit_plan_id`` is the prefixed
 * ``bpln_*`` form rather than a raw UUID.
 */
export interface ContributionTier {
    /** Prefixed benefit-plan identifier (`bpln_*`). */
    benefit_plan_id: string;
    /** Benefit plan name. */
    benefit_plan_name: string;
    /** Coverage-tier name. */
    benefit_plan_tier_name: string;
    /**
     * Coverage-tier code for this tier.
     *
     * * `Unspecified` - Unspecified
     * * `EE` - Ee
     * * `ES` - Es
     * * `EC` - Ec
     * * `EF` - Ef
     */
    coverage_tier: VitableConnect.CoverageTier;
    /** Monthly employee deduction in cents. */
    cost: number;
    /** Monthly employee deduction per dependent, in cents. */
    cost_per_dependent: number;
    /** Whether dependents are required for this tier. */
    dependents_required_in: boolean;
    /** Whether a spouse is required for this tier. */
    spouse_required_in: boolean;
}
