// This file was auto-generated by Fern from our API Definition.

/**
 * * `Unspecified` - Unspecified
 * * `State` - State
 */
export const ContributionClassLocation = {
    Unspecified: "Unspecified",
    State: "State",
} as const;
export type ContributionClassLocation = (typeof ContributionClassLocation)[keyof typeof ContributionClassLocation];
