// This file was auto-generated by Fern from our API Definition.

export interface ContributionRange {
    /** Lowest per-tier contribution in cents. */
    min_cents: number;
    /** Highest per-tier contribution in cents. */
    max_cents: number;
}
