// This file was auto-generated by Fern from our API Definition.

/**
 * * `Unspecified` - Unspecified
 * * `Full Time` - Full Time
 * * `Part Time` - Part Time
 * * `Temporary` - Temporary
 * * `Seasonal` - Seasonal
 */
export const ContributionClassEmployment = {
    Unspecified: "Unspecified",
    FullTime: "Full Time",
    PartTime: "Part Time",
    Temporary: "Temporary",
    Seasonal: "Seasonal",
} as const;
export type ContributionClassEmployment =
    (typeof ContributionClassEmployment)[keyof typeof ContributionClassEmployment];
