// This file was auto-generated by Fern from our API Definition.

/**
 * * `Unspecified` - Unspecified
 * * `EE` - EE
 * * `ES` - ES
 * * `EC` - EC
 * * `EF` - EF
 */
export const CoverageTier = {
    Unspecified: "Unspecified",
    Ee: "EE",
    Es: "ES",
    Ec: "EC",
    Ef: "EF",
} as const;
export type CoverageTier = (typeof CoverageTier)[keyof typeof CoverageTier];
