// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface CreateMemberDependentAddressRequest {
    /** Primary street address */
    address_line_1: string;
    /** Secondary street address */
    address_line_2?: (string | null) | undefined;
    /** City name */
    city: string;
    /**
     * Two-letter state code
     *
     * * `AL` - AL
     * * `AK` - AK
     * * `AZ` - AZ
     * * `AR` - AR
     * * `CA` - CA
     * * `CO` - CO
     * * `CT` - CT
     * * `DC` - DC
     * * `DE` - DE
     * * `FL` - FL
     * * `GA` - GA
     * * `HI` - HI
     * * `ID` - ID
     * * `IL` - IL
     * * `IN` - IN
     * * `IA` - IA
     * * `KS` - KS
     * * `KY` - KY
     * * `LA` - LA
     * * `ME` - ME
     * * `MD` - MD
     * * `MA` - MA
     * * `MI` - MI
     * * `MN` - MN
     * * `MS` - MS
     * * `MO` - MO
     * * `MT` - MT
     * * `NE` - NE
     * * `NV` - NV
     * * `NH` - NH
     * * `NJ` - NJ
     * * `NM` - NM
     * * `NY` - NY
     * * `NC` - NC
     * * `ND` - ND
     * * `OH` - OH
     * * `OK` - OK
     * * `OR` - OR
     * * `PA` - PA
     * * `RI` - RI
     * * `SC` - SC
     * * `SD` - SD
     * * `TN` - TN
     * * `TX` - TX
     * * `UT` - UT
     * * `VT` - VT
     * * `VA` - VA
     * * `WA` - WA
     * * `WI` - WI
     * * `WV` - WV
     * * `WY` - WY
     * * `PR` - PR
     * * `GU` - GU
     * * `AS` - AS
     * * `VI` - VI
     * * `MP` - MP
     * * `MH` - MH
     * * `PW` - PW
     * * `FM` - FM
     * * `AE` - AE
     * * `AA` - AA
     * * `AP` - AP
     */
    state: VitableConnect.State;
    /** ZIP code */
    zipcode: string;
}
