// This file was auto-generated by Fern from our API Definition.

/**
 * * `BROKERAGE` - BROKERAGE
 * * `TPA` - TPA
 * * `GENERAL_AGENT` - GENERAL_AGENT
 * * `CHANNEL_PARTNER` - CHANNEL_PARTNER
 * * `CONSULTING_FIRM` - CONSULTING_FIRM
 * * `API_PLATFORM` - API_PLATFORM
 */
export const CreateOrganizationRequestType = {
    Brokerage: "BROKERAGE",
    Tpa: "TPA",
    GeneralAgent: "GENERAL_AGENT",
    ChannelPartner: "CHANNEL_PARTNER",
    ConsultingFirm: "CONSULTING_FIRM",
    ApiPlatform: "API_PLATFORM",
} as const;
export type CreateOrganizationRequestType =
    (typeof CreateOrganizationRequestType)[keyof typeof CreateOrganizationRequestType];
