// This file was auto-generated by Fern from our API Definition.

/**
 * * `weekly` - Weekly
 * * `bi_weekly` - Bi Weekly
 * * `semi_monthly` - Semi Monthly
 * * `monthly` - Monthly
 */
export const DeductionFrequency = {
    Weekly: "weekly",
    BiWeekly: "bi_weekly",
    SemiMonthly: "semi_monthly",
    Monthly: "monthly",
} as const;
export type DeductionFrequency = (typeof DeductionFrequency)[keyof typeof DeductionFrequency];
