// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface DetailedAddress {
    address_line_1: string;
    address_line_2?: (string | null) | undefined;
    city: string;
    zipcode: string;
    state: VitableConnect.State;
    latitude?: (number | null) | undefined;
    longitude?: (number | null) | undefined;
    county_fips_code?: (string | null) | undefined;
    county_name?: (string | null) | undefined;
}
