// This file was auto-generated by Fern from our API Definition.

export const ElectionStatusItem = {
    Enrolled: "Enrolled",
    Expired: "Expired",
    Pending: "Pending",
    Waived: "Waived",
} as const;
export type ElectionStatusItem = (typeof ElectionStatusItem)[keyof typeof ElectionStatusItem];
