// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface EligibleGeographicalLocation {
    /**
     * `All` (unrestricted) or `StateCodes` (restricted to `state_codes`).
     *
     * * `All` - All
     * * `StateCodes` - State Codes
     */
    type: VitableConnect.EligibleGeographicalLocationType;
    /** States the rule is restricted to; empty when `type` is `All`. */
    state_codes: string[];
}
