// This file was auto-generated by Fern from our API Definition.

/**
 * * `All` - All
 * * `StateCodes` - State Codes
 */
export const EligibleGeographicalLocationType = {
    All: "All",
    StateCodes: "StateCodes",
} as const;
export type EligibleGeographicalLocationType =
    (typeof EligibleGeographicalLocationType)[keyof typeof EligibleGeographicalLocationType];
