// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * The plan year's active eligibility policy. Mirrors the internal ``PlanYearEligibilityPolicyDTO``
 * but exposes only the public subset (no raw ids, ``active_in``, or timestamps).
 */
export interface EligibilityPolicy {
    /**
     * When coverage starts for a newly-eligible member, or null.
     *
     * * `FIRST_OF_FOLLOWING_MONTH` - First Of Following Month
     * * `THIRTY_DAYS` - Thirty Days
     * * `SIXTY_DAYS` - Sixty Days
     */
    waiting_period: VitableConnect.WaitingPeriod | null;
    /**
     * When coverage ends after a member becomes ineligible.
     *
     * * `END_OF_N_MONTHS` - End Of N Months
     * * `END_OF_PLAN_YEAR` - End Of Plan Year
     */
    termination_rule: VitableConnect.TerminationRule;
    /** Months of continued coverage; set only when `termination_rule` is `END_OF_N_MONTHS`. */
    termination_n_months: number | null;
    /** Eligibility rules; never empty for a valid policy. */
    rules: VitableConnect.EligibilityPolicyRule[];
}
