// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * One eligibility rule — the workforce slice it makes eligible. Mirrors the internal
 * ``PlanYearEligibilityPolicyRuleDTO`` minus the raw ids and timestamps.
 */
export interface EligibilityPolicyRule {
    /**
     * Employee-class matcher (`All` for any).
     *
     * * `Full Time` - Full Time
     * * `Part Time` - Part Time
     * * `Temporary` - Temporary
     * * `Intern` - Intern
     * * `Seasonal` - Seasonal
     * * `Individual Contractor` - Individual Contractor
     * * `All` - All
     */
    employee_class: VitableConnect.EligibilityRuleEmployeeClass;
    /**
     * Compensation matcher (`All` for any).
     *
     * * `Salary` - Salary
     * * `Hourly` - Hourly
     * * `All` - All
     */
    compensation_type: VitableConnect.EligibilityRuleCompensationType;
    /** Geographic matcher. */
    eligible_geographical_location: VitableConnect.EligibleGeographicalLocation;
}
