// This file was auto-generated by Fern from our API Definition.

/**
 * * `Salary` - Salary
 * * `Hourly` - Hourly
 * * `All` - All
 */
export const EligibilityRuleCompensationType = {
    Salary: "Salary",
    Hourly: "Hourly",
    All: "All",
} as const;
export type EligibilityRuleCompensationType =
    (typeof EligibilityRuleCompensationType)[keyof typeof EligibilityRuleCompensationType];
