// This file was auto-generated by Fern from our API Definition.

export interface EmployeeAddressInput {
    /** Primary street address */
    street_1: string;
    /** Secondary street address */
    street_2?: (string | null) | undefined;
    /** City name */
    city: string;
    /** Two-letter state code */
    state: string;
    /** ZIP code */
    zip_code: string;
    /** Country code */
    country?: string | undefined;
}
