// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single employer settings resource.
 */
export interface EmployerSettingsResponse {
    /** The employer's current settings. */
    data: VitableConnect.EmployerSettings;
}
