// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface EmployerHris {
    /** HRIS connection details, or null when the employer has no integration. */
    hris: VitableConnect.HrisConnection | null;
}
