// This file was auto-generated by Fern from our API Definition.

export interface EmployerBenefitLifecycleStage {
    /** Computed employer benefit-lifecycle stage: `open_enrollment`, `renewal`, `active`, `onboarding`, or `cancelled`. */
    stage: string;
    /** Anchor date for the stage (e.g. renewal date); null when not applicable. */
    as_of_date: string | null;
}
