// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface EmployerSettings {
    /**
     * Payroll deduction frequency. One of: weekly, bi_weekly, semi_monthly, monthly
     *
     * * `weekly` - Weekly
     * * `bi_weekly` - Bi-Weekly
     * * `semi_monthly` - Semi-Monthly
     * * `monthly` - Monthly
     */
    pay_frequency: VitableConnect.DeductionFrequency | null;
}
