// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Serializer for Employer entity in public API responses.
 */
export interface Employer {
    /** Unique employer identifier with 'empr_' prefix */
    id?: string | undefined;
    /** ID of the parent organization (org_*) */
    organization_id?: (string | null) | undefined;
    /** Display name of the employer */
    name: string;
    /** Legal business name for compliance and tax purposes */
    legal_name: string;
    /** Employer Identification Number (format: XX-XXXXXXX) */
    ein?: (string | null) | undefined;
    /** Partner-assigned reference ID for the employer */
    reference_id?: (string | null) | undefined;
    /** Email address for billing and communications */
    email?: (string | null) | undefined;
    /** Employer phone number (E.164 format recommended) */
    phone_number?: (string | null) | undefined;
    /** Whether the employer is currently active in the system */
    active: boolean;
    /** Employer's primary address */
    address: VitableConnect.EmployerAddress;
    /** Primary company-admin contact, or null */
    contact?: (VitableConnect.EmployerContact | null) | undefined;
    /** Timestamp when the employer was created */
    created_at: string;
    /** Timestamp when the employer was last updated */
    updated_at: string;
}
