// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface EmployerBenefitPlanYearsListResponse {
    /** The employer's benefit plan years, newest first. */
    data: VitableConnect.BenefitPlanYearList[];
}
