// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single employer benefit plan year resource.
 */
export interface EmployerBenefitPlanYearResponse {
    /** The benefit plan year, including its plans and contribution rules. */
    data: VitableConnect.BenefitPlanYearDetail;
}
