// This file was auto-generated by Fern from our API Definition.

export interface EmployerAddressInput {
    /** Primary street address */
    address_line_1: string;
    /** Secondary street address */
    address_line_2?: (string | null) | undefined;
    /** City name */
    city: string;
    /** Two-letter state code */
    state: string;
    /** ZIP code */
    zipcode: string;
}
