// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single employer invoice pdf resource.
 */
export interface EmployerInvoicePdfResponse {
    /** A short-lived download link for the invoice PDF. */
    data: VitableConnect.EmployerInvoicePdf;
}
