// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing employee resources.
 */
export interface EmployeeListResponse {
    /** This page of employees. */
    data: VitableConnect.Employee[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
