// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing employer payroll deduction statement resources.
 */
export interface EmployerPayrollDeductionStatementListResponse {
    /** This page of payroll deduction statements. */
    data: VitableConnect.PayrollDeductionStatement[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
