// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Cursor-paginated invoices envelope: ``{ "data": [...], "pagination": { "next_offset": ... } }``.
 */
export interface EmployerInvoicesListResponse {
    /** This page of invoices. */
    data: VitableConnect.Invoice[];
    /** Cursor metadata for this result set. */
    pagination: VitableConnect.InvoicesCursorPagination;
}
