// This file was auto-generated by Fern from our API Definition.

/**
 * Primary company-admin contact (email + phone; company admins have no person name).
 */
export interface EmployerContact {
    /** Primary contact email */
    email: string | null;
    /** Primary contact phone, or null */
    phone: string | null;
}
