// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single employer hris resource.
 */
export interface EmployerHrisResponse {
    /** The employer's HRIS connection, or `null` when no integration exists. */
    data: VitableConnect.EmployerHris;
}
