// This file was auto-generated by Fern from our API Definition.

export const EmployeeStatus = {
    Active: "active",
    Terminated: "terminated",
} as const;
export type EmployeeStatus = (typeof EmployeeStatus)[keyof typeof EmployeeStatus];
