// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single employee resource.
 */
export interface EmployeeResponse {
    /** The employee record. */
    data: VitableConnect.Employee;
}
