// This file was auto-generated by Fern from our API Definition.

/**
 * Case-insensitive search. Matches member name partially, and the `member_id` exactly — either your own reference id or the prefixed `grpmbr_<...>` id.
 */
export type EmployerSearch = string;
