// This file was auto-generated by Fern from our API Definition.

export interface EnrollmentRateSummary {
    /** Employees eligible for at least one active benefit. */
    eligible: number;
    /** Employees enrolled in at least one active benefit. */
    enrolled: number;
    /** ``enrolled / eligible`` as a whole-number percent (0 when none eligible). */
    percentage: number;
}
