// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single enrollment resource.
 */
export interface EnrollmentResponse {
    /** The enrollment, including its elected plans. */
    data: VitableConnect.EnrollmentDetail;
}
