// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponse {
    /** ISO 8601 timestamp when the error occurred */
    timestamp: string;
    /** Human-readable error message */
    message: string;
    /** Error message (same as message, for backwards compatibility) */
    error: string;
    /** Application-specific error code for programmatic handling */
    app_error_code?: (string | null) | undefined;
    /** Unique trace ID for debugging and support requests */
    trace_id: string;
}
