// This file was auto-generated by Fern from our API Definition.

/**
 * * `enrollment.accepted` - Enrollment Accepted
 * * `enrollment.terminated` - Enrollment Terminated
 * * `enrollment.termination_rescheduled` - Enrollment Termination Rescheduled
 * * `enrollment.elected` - Enrollment Elected
 * * `enrollment.granted` - Enrollment Granted
 * * `enrollment.waived` - Enrollment Waived
 * * `enrollment.started` - Enrollment Started
 * * `employee.eligibility_granted` - Employee Eligibility Granted
 * * `employee.eligibility_terminated` - Employee Eligibility Terminated
 * * `employee.deactivated` - Employee Deactivated
 * * `employee.deduction_created` - Employee Deduction Created
 */
export const EventName = {
    EnrollmentAccepted: "enrollment.accepted",
    EnrollmentTerminated: "enrollment.terminated",
    EnrollmentTerminationRescheduled: "enrollment.termination_rescheduled",
    EnrollmentElected: "enrollment.elected",
    EnrollmentGranted: "enrollment.granted",
    EnrollmentWaived: "enrollment.waived",
    EnrollmentStarted: "enrollment.started",
    EmployeeEligibilityGranted: "employee.eligibility_granted",
    EmployeeEligibilityTerminated: "employee.eligibility_terminated",
    EmployeeDeactivated: "employee.deactivated",
    EmployeeDeductionCreated: "employee.deduction_created",
} as const;
export type EventName = (typeof EventName)[keyof typeof EventName];
