// This file was auto-generated by Fern from our API Definition.

/** * `client_credentials` - client_credentials */
export const GrantType = {
    ClientCredentials: "client_credentials",
} as const;
export type GrantType = (typeof GrantType)[keyof typeof GrantType];
