// This file was auto-generated by Fern from our API Definition.

export interface Group {
    /** Prefixed group identifier (`grp_<base64-encoded-uuid>`). */
    id: string;
    /** Prefixed organization identifier (`org_<base64-encoded-uuid>`). */
    organization_id: string;
    /** Human-readable group name. */
    name: string;
    /** Stable identifier for this group in the integrator's own system. */
    external_reference_id: string;
    /** Group creation timestamp (ISO 8601, UTC). */
    created_at: string | null;
    /** Last-update timestamp (ISO 8601, UTC). */
    updated_at: string | null;
}
