// This file was auto-generated by Fern from our API Definition.

export interface GroupMemberSyncResponse {
    /** Identifier for this sync request. Pass it to `GET /v1/groups/{group_id}/members/sync/{request_id}` to poll for results. */
    request_id: string;
    /** Group whose roster is being synced (`grp_*`). */
    group_id: string;
    /** When Vitable accepted the sync request for processing (RFC 3339). */
    accepted_at: string;
}
