// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single group resource.
 */
export interface GroupResponse {
    /** The group record. */
    data: VitableConnect.Group;
}
