// This file was auto-generated by Fern from our API Definition.

/**
 * * `add` - add
 * * `remove` - remove
 */
export const GroupMemberSyncFailureOperation = {
    Add: "add",
    Remove: "remove",
} as const;
export type GroupMemberSyncFailureOperation =
    (typeof GroupMemberSyncFailureOperation)[keyof typeof GroupMemberSyncFailureOperation];
