// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface GroupMemberSyncFailure {
    /** Your identifier for the member that failed to sync. */
    reference_id: string;
    /** The sync operation that failed for this member. */
    operation: VitableConnect.Operation;
    /** Human-readable explanation of why the operation failed. */
    reason: string;
}
