// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single group member sync request detail resource.
 */
export interface GroupMemberSyncRequestDetailResponse {
    /** The group member sync request, including per-member results. */
    data: VitableConnect.GroupMemberSyncRequestDetail;
}
