// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single group member sync detail resource.
 */
export interface GroupMemberSyncDetailResponse {
    /** The group member sync request, including its current processing status. */
    data: VitableConnect.GroupMemberSyncResponse;
}
