// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface GroupMemberSyncMemberRequest {
    /** Your own identifier for this member. Vitable echoes it back on sync failures so you can match them to your records. */
    reference_id: string;
    /** Member's legal first name. */
    first_name: string;
    /** Member's legal last name. */
    last_name: string;
    /** Member's date of birth as `YYYY-MM-DD`. */
    date_of_birth: string;
    /** Member's contact phone number in E.164 format. */
    phone?: (string | null) | undefined;
    /** Plan the member should be subscribed to (`plan_*`). */
    plan_id: string;
    /** The member's postal address. */
    address: VitableConnect.AddressRequest;
    /** Member's email address. Vitable sends care and coverage notices here. */
    email?: (string | null) | undefined;
}
