// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface GroupMemberSyncResults {
    /** IDs of members added to the group by this sync. */
    added_group_member_ids: string[];
    /** IDs of members removed from the group by this sync. */
    removed_group_member_ids: string[];
    /** Members that could not be synced, with a reason for each. */
    failures: VitableConnect.GroupMemberSyncFailure[];
}
