// This file was auto-generated by Fern from our API Definition.

/**
 * * `Child` - Child
 * * `Spouse` - Spouse
 * * `Roommate` - Roommate
 * * `Other` - Other
 */
export const HouseholdMemberRelationship = {
    Child: "Child",
    Spouse: "Spouse",
    Roommate: "Roommate",
    Other: "Other",
} as const;
export type HouseholdMemberRelationship =
    (typeof HouseholdMemberRelationship)[keyof typeof HouseholdMemberRelationship];
