// This file was auto-generated by Fern from our API Definition.

/**
 * * `Account Holder` - Account Holder
 * * `Dependent` - Dependent
 * * `Inactive` - Inactive
 */
export const HouseholdMemberType = {
    AccountHolder: "Account Holder",
    Dependent: "Dependent",
    Inactive: "Inactive",
} as const;
export type HouseholdMemberType = (typeof HouseholdMemberType)[keyof typeof HouseholdMemberType];
