// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Wire serializer for :class:`HouseholdMemberDTO` (one household participant).
 */
export interface HouseholdMember {
    /** Member identifier with 'mbr_' prefix */
    member_id?: string | undefined;
    /** Household member's first name */
    first_name: string;
    /** Household member's last name */
    last_name: string;
    /**
     * Relationship to the head of household; null for the account holder themselves
     *
     * * `Child` - Child
     * * `Spouse` - Spouse
     * * `Roommate` - Roommate
     * * `Other` - Other
     */
    relationship?: (VitableConnect.HouseholdMemberRelationship | null) | undefined;
    /**
     * What this participant is to the household: `Account Holder`, `Dependent`, or `Inactive`.
     *
     * * `Account Holder` - Account Holder
     * * `Dependent` - Dependent
     * * `Inactive` - Inactive
     */
    member_type: VitableConnect.HouseholdMemberType;
    /** Date of birth (YYYY-MM-DD) */
    date_of_birth: string;
    /** Whether this participant is a household admin (the account holder always is) */
    household_admin_in: boolean;
}
