// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Unpaginated ``{"data": [...]}`` list of the members of a member's household.
 */
export interface HouseholdMembersResponse {
    /** The members of the household. */
    data: VitableConnect.HouseholdMember[];
}
