// This file was auto-generated by Fern from our API Definition.

/**
 * * `Pending` - Pending
 * * `Active` - Active
 * * `Inactive` - Inactive
 * * `Paused` - Paused
 * * `Terminated` - Terminated
 */
export const HrisStatusItem = {
    Pending: "Pending",
    Active: "Active",
    Inactive: "Inactive",
    Paused: "Paused",
    Terminated: "Terminated",
} as const;
export type HrisStatusItem = (typeof HrisStatusItem)[keyof typeof HrisStatusItem];
