// This file was auto-generated by Fern from our API Definition.

export interface HrisConnection {
    /** Id of the HRIS/payroll provider the employer is connected to (e.g. `paylocity`). */
    provider: string;
    /** Display name of that provider (e.g. `Paylocity`). */
    provider_label: string;
    /** Connection status reported by the integration. */
    status: string;
    /** When the last sync completed, or null when none has. */
    last_sync_on: string | null;
    /** Rows in the latest completed sync, or null when none has. */
    synced_row_count: number | null;
}
