// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * One ICHRA contribution class, mirroring the internal configuration endpoint's
 * ``IchraContributionClassConfigurationEntitySerializer`` field-for-field. Two deliberate
 * differences for the public surface: the identifier is the opaque prefixed ``iccl_*`` form rather
 * than a raw UUID, and the matcher choices come from the domain enums rather than the model's.
 */
export interface IchraContributionClass {
    /** Prefixed contribution-class identifier (`iccl_*`). */
    contribution_class_id: string;
    /** Monthly allowance in cents. */
    amount_in_cents: number;
    /**
     * Employment matcher.
     *
     * * `Unspecified` - Unspecified
     * * `Full Time` - Full Time
     * * `Part Time` - Part Time
     * * `Temporary` - Temporary
     * * `Seasonal` - Seasonal
     */
    employment: VitableConnect.ContributionClassEmployment;
    /**
     * Compensation matcher.
     *
     * * `Unspecified` - Unspecified
     * * `Salary` - Salary
     * * `Hourly` - Hourly
     */
    compensation: VitableConnect.ContributionClassCompensation;
    /**
     * Location matcher type.
     *
     * * `Unspecified` - Unspecified
     * * `State` - State
     */
    location: VitableConnect.ContributionClassLocation;
    /** Location matcher value (CSV of state codes), or null. */
    location_value: string | null;
    /**
     * Family-status matcher.
     *
     * * `Unspecified` - Unspecified
     * * `EE` - Ee
     * * `ES` - Es
     * * `EC` - Ec
     * * `EF` - Ef
     */
    family_status: VitableConnect.CoverageTier;
    /** Age-band lower bound, or null. */
    min_age: number | null;
    /** Age-band upper bound, or null. */
    max_age: number | null;
}
