// This file was auto-generated by Fern from our API Definition.

/**
 * * `workos` - WorkOS
 * * `vitable` - Vitable
 */
export const IdpProvider = {
    Workos: "workos",
    Vitable: "vitable",
} as const;
export type IdpProvider = (typeof IdpProvider)[keyof typeof IdpProvider];
