// This file was auto-generated by Fern from our API Definition.

/**
 * Include cancelled employers (hidden by default unless their stage is explicitly requested).
 */
export type IncludeCancelled = boolean;
