// This file was auto-generated by Fern from our API Definition.

export interface InvoicesCursorPagination {
    /** Opaque JSON-encoded cursor for the next page; null when there are no more pages. */
    next_offset: string | null;
}
