// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface ListWebhookEventDeliveriesResponse {
    /** Delivery attempts for the webhook event, most recent first. */
    data: VitableConnect.WebhookDelivery[];
}
