// This file was auto-generated by Fern from our API Definition.

/**
 * * `Single` - Single
 * * `Married` - Married
 */
export const MaritalStatus = {
    Single: "Single",
    Married: "Married",
} as const;
export type MaritalStatus = (typeof MaritalStatus)[keyof typeof MaritalStatus];
