// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Unpaginated ``{"data": [...]}`` list of member digital benefit cards.
 */
export interface MemberDigitalBenefitCardsResponse {
    /** The member's digital benefit cards. */
    data: VitableConnect.DigitalBenefitCard[];
}
