// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Unpaginated ``{"data": [...]}`` list of member employments.
 */
export interface MemberEmploymentsResponse {
    /** The member's employment records, one per employer. */
    data: VitableConnect.Employee[];
}
