// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface MemberAddress {
    /** Primary street address */
    address_line_1: string;
    /** Secondary street address (apt, suite, etc.) */
    address_line_2?: (string | null) | undefined;
    /** City name */
    city: string;
    /**
     * Two-letter state code (e.g., CA, NY)
     *
     * * `AL` - Al
     * * `AK` - Ak
     * * `AZ` - Az
     * * `AR` - Ar
     * * `CA` - Ca
     * * `CO` - Co
     * * `CT` - Ct
     * * `DC` - Dc
     * * `DE` - De
     * * `FL` - Fl
     * * `GA` - Ga
     * * `HI` - Hi
     * * `ID` - Id
     * * `IL` - Il
     * * `IN` - In
     * * `IA` - Ia
     * * `KS` - Ks
     * * `KY` - Ky
     * * `LA` - La
     * * `ME` - Me
     * * `MD` - Md
     * * `MA` - Ma
     * * `MI` - Mi
     * * `MN` - Mn
     * * `MS` - Ms
     * * `MO` - Mo
     * * `MT` - Mt
     * * `NE` - Ne
     * * `NV` - Nv
     * * `NH` - Nh
     * * `NJ` - Nj
     * * `NM` - Nm
     * * `NY` - Ny
     * * `NC` - Nc
     * * `ND` - Nd
     * * `OH` - Oh
     * * `OK` - Ok
     * * `OR` - Or
     * * `PA` - Pa
     * * `RI` - Ri
     * * `SC` - Sc
     * * `SD` - Sd
     * * `TN` - Tn
     * * `TX` - Tx
     * * `UT` - Ut
     * * `VT` - Vt
     * * `VA` - Va
     * * `WA` - Wa
     * * `WI` - Wi
     * * `WV` - Wv
     * * `WY` - Wy
     * * `PR` - Pr
     * * `GU` - Gu
     * * `AS` - As
     * * `VI` - Vi
     * * `MP` - Mp
     * * `MH` - Mh
     * * `PW` - Pw
     * * `FM` - Fm
     * * `AE` - Ae
     * * `AA` - Aa
     * * `AP` - Ap
     */
    state: VitableConnect.State;
    /** ZIP code (5 or 9 digit) */
    zipcode: string;
}
