// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single member resource.
 */
export interface MemberResponse {
    /** The member record. */
    data: VitableConnect.Member;
}
