// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing member resources.
 */
export interface MemberListResponse {
    /** This page of members. */
    data: VitableConnect.MemberListItem[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
