// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface MemberQualifyingLifeEvent {
    /** Opaque qualifying life event identifier */
    id: string;
    /**
     * The member-submitted qualifying life event type
     *
     * * `lost_job_based_coverage` - Losing job-based health insurance
     * * `aged_off_parent_plan` - Aging off a parent's plan at age 26
     * * `lost_medicaid_chip_medicare` - Losing Medicaid, CHIP, or Medicare eligibility
     * * `lost_decertified_individual_plan` - Losing individual coverage because a plan was decertified
     * * `married` - Getting married
     * * `divorced` - Getting divorced or legally separated
     * * `had_baby` - Having a baby
     * * `adopted_child` - Adopting a child
     * * `foster_care_placement` - Foster-care placement
     * * `death_of_spouse_or_dependent` - Death of a covered spouse or dependent
     * * `court_ordered` - Court order to add a dependent
     * * `moved_to_new_coverage_area` - Moving to a new ZIP code, county, or state where different plans are available
     * * `moved_to_us` - Moving to the U.S. from another country
     * * `moved_to_or_from_school_housing` - Moving to or from school housing
     * * `moved_to_or_from_seasonal_work_housing` - Moving to or from housing for seasonal work
     * * `became_us_citizen` - Becoming a U.S. citizen
     * * `left_incarceration` - Leaving incarceration
     * * `gained_tribal_status` - Gaining status as a member of a federally recognized tribe or Alaska Native corporation
     * * `started_or_ended_americorps_service` - Starting or ending AmeriCorps service
     * * `new_child` - New child
     * * `other` - Other
     */
    event_type: VitableConnect.QualifyingLifeEventType;
    /** Human-readable label for event_type */
    event_type_label: string;
    /** Custom event description when event_type is Other; otherwise normally null */
    other_event: string | null;
    /**
     * Review status of the qualifying life event
     *
     * * `pending` - Pending
     * * `approved` - Approved
     * * `denied` - Denied
     */
    status: VitableConnect.QualifyingLifeEventStatus;
    /** When the member submitted the event */
    submitted_at: string;
}
