// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Unpaginated ``{"data": [...]}`` list of member dependents.
 */
export interface MemberDependentsResponse {
    /** The member's legal dependents. */
    data: VitableConnect.MemberLegalDependent[];
}
