// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Wire serializer for :class:`MemberEnrollmentDTO` (one benefit enrollment row).
 */
export interface MemberEnrollment {
    /** Opaque, stable enrollment identifier used to target enrollment actions */
    id: string;
    /** Exact employer identifier for this enrollment */
    employer_id: string;
    /** Exact benefit plan-year identifier for this enrollment */
    benefit_plan_year_id: string;
    /**
     * High-level benefit grouping (e.g., Medical, Dental)
     *
     * * `Medical` - Medical
     * * `Dental` - Dental
     * * `Vision` - Vision
     * * `Hospital` - Hospital
     */
    benefit_type: VitableConnect.Category;
    /**
     * The benefit product this enrollment is for
     *
     * * `EBA` - Eba Mec
     * * `VPC` - Vpc Enhanced
     * * `VPC_CORE` - Vpc Core
     * * `MEC` - Vpc Mec
     * * `MEC2` - Mec2
     * * `MEC_PLUS` - Mec Plus
     * * `MVP` - Mvp
     * * `MVP2` - Mvp2
     * * `MVPSL` - Mvpsl
     * * `MVPSL2` - Mvpsl2
     * * `VD` - Dental
     * * `VV` - Vision
     * * `ICHRA` - Ichra
     * * `ICHRA_PREMIUM_PLUS` - Ichra Premium Plus
     * * `ICHRA_REIMBURSEMENT_ONLY` - Ichra Reimbursement Only
     */
    product_code: VitableConnect.ProductCode;
    /** Whether a qualifying life event would be required to reissue this enrollment under the product and open-enrollment rule at the time this list was read */
    requires_qle_for_reissue: boolean;
    /** Display name of the benefit product */
    product_name: string;
    /** Name of the employer the enrollment is through */
    employer_name: string;
    /** Insurance carrier name; null when no active carrier period is resolvable */
    carrier_name?: (string | null) | undefined;
    /** Chosen benefit plan name; null unless the row is an election */
    plan_name?: (string | null) | undefined;
    /** Chosen benefit plan tier name (e.g., Employee Only); null unless the row is an election */
    tier_name?: (string | null) | undefined;
    /** Employee monthly payroll deduction in cents; null unless the row is an election */
    employee_deduction_in_cents?: (number | null) | undefined;
    /** Employer monthly contribution in cents; null unless the row is an election */
    employer_contribution_in_cents?: (number | null) | undefined;
    /** Total monthly plan premium in cents; null unless the row is an election */
    premium_in_cents?: (number | null) | undefined;
    /** Coverage window start date (YYYY-MM-DD) */
    coverage_start?: (string | null) | undefined;
    /** Coverage window end date (YYYY-MM-DD); null while coverage is open-ended */
    coverage_end?: (string | null) | undefined;
    /** Earliest applicable coverage boundary (YYYY-MM-DD) when coverage was cancelled before its effective start; null unless the enrollment was cancelled */
    cancelled_date: string | null;
    /** Benefit plan-year coverage end date (YYYY-MM-DD), distinct from this enrollment's coverage_end; null when the plan year is open-ended */
    plan_year_coverage_end: string | null;
    /** Date the enrollment record was created (YYYY-MM-DD), the value Ops labels Issued on. Present on every row whatever the member answered, and distinct from `coverage_start`. It equals `enrollment_window_start` for a row issued once its open enrollment had already opened, and precedes it for a row issued ahead of open enrollment. */
    issued_date: string;
    /** First date the member could answer this enrollment (YYYY-MM-DD). Open enrollment's start date for a row issued before open enrollment opened, otherwise the date the row was issued -- an enrollment is never answerable before it exists, so this is never earlier than `issued_date`. */
    enrollment_window_start: string;
    /** Enrollment / open-enrollment window end date (YYYY-MM-DD); null when open-ended */
    enrollment_window_end?: (string | null) | undefined;
    /**
     * Where the member stands: `Enrolled` or `Waived` if they answered, otherwise `Pending` while their enrollment window is open and `Expired` once it has closed.
     *
     * * `Enrolled` - Enrolled
     * * `Waived` - Waived
     * * `Pending` - Pending
     * * `Expired` - Expired
     */
    election_status: VitableConnect.PlanYearEnrollmentElectionStatus;
    /**
     * Where the member's coverage stands: `Coverage Upcoming`, `Coverage Effective`, `Coverage Ended`, or `Cancelled`. Null unless the member enrolled.
     *
     * * `Coverage Upcoming` - Coverage Upcoming
     * * `Coverage Effective` - Coverage Effective
     * * `Coverage Ended` - Coverage Ended
     * * `Cancelled` - Cancelled
     */
    policy_status: VitableConnect.PlanYearEnrollmentPolicyStatus | null;
    /** True when today falls in the final month of the plan-year coverage window; drives end-of-coverage enrollment actions on the client. */
    in_last_month_of_coverage: boolean;
    /** True when today falls inside the enrollment window this member has to answer in; drives enrollment-action availability on the client. */
    is_within_enrollment_window: boolean;
}
