// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * A member in the organization's directory: identity, contact details, address, and join date.
 */
export interface MemberListItem {
    /** Unique member identifier with 'mbr_' prefix */
    id?: string | undefined;
    /** Member's legal first name */
    first_name: string;
    /** Member's legal last name */
    last_name: string;
    /** Email address */
    email?: (string | null) | undefined;
    /** Phone number (10-digit US domestic string) */
    phone?: (string | null) | undefined;
    /** Member's residential address */
    address?: (VitableConnect.MemberAddress | null) | undefined;
}
