// This file was auto-generated by Fern from our API Definition.

export const MemberStatus = {
    Onboarded: "onboarded",
    PendingOnboarding: "pending_onboarding",
} as const;
export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];
