// This file was auto-generated by Fern from our API Definition.

/**
 * * `EMAIL_CENSUS` - EMAIL_CENSUS
 * * `SECOND_SYSTEM_ACCESS` - SECOND_SYSTEM_ACCESS
 */
export const MissingEmployeeResolution = {
    EmailCensus: "EMAIL_CENSUS",
    SecondSystemAccess: "SECOND_SYSTEM_ACCESS",
} as const;
export type MissingEmployeeResolution = (typeof MissingEmployeeResolution)[keyof typeof MissingEmployeeResolution];
