// This file was auto-generated by Fern from our API Definition.

/**
 * * `Sr` - Sr
 * * `Jr` - Jr
 * * `I` - I
 * * `II` - II
 * * `III` - III
 * * `IV` - IV
 * * `V` - V
 */
export const NameSuffix = {
    Sr: "Sr",
    Jr: "Jr",
    I: "I",
    Ii: "II",
    Iii: "III",
    Iv: "IV",
    V: "V",
} as const;
export type NameSuffix = (typeof NameSuffix)[keyof typeof NameSuffix];
