// This file was auto-generated by Fern from our API Definition.

/**
 * * `add` - add
 * * `remove` - remove
 */
export const Operation = {
    Add: "add",
    Remove: "remove",
} as const;
export type Operation = (typeof Operation)[keyof typeof Operation];
