// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface OrganizationMembership {
    /** Prefixed organization identifier (`org_<base64-encoded-uuid>`). */
    id: string;
    /** Human-readable organization name. */
    name: string;
    /**
     * Partner type (e.g. BROKERAGE, TPA).
     *
     * * `BROKERAGE` - Brokerage
     * * `TPA` - TPA
     * * `GENERAL_AGENT` - General Agent
     * * `CHANNEL_PARTNER` - Channel Partner
     * * `CONSULTING_FIRM` - Consulting Firm
     * * `API_PLATFORM` - API Platform
     */
    type: VitableConnect.OrganizationType | null;
    /** IdP-issued tenant id (WorkOS org id). */
    idp_org_id: string | null;
    /**
     * IdP that minted idp_org_id (e.g. 'workos').
     *
     * * `workos` - WorkOS
     * * `vitable` - Vitable
     */
    idp_provider: VitableConnect.IdpProvider | null;
    /** Whether this organization reads across every organization. */
    super_in: boolean;
    /**
     * The caller's role in this organization.
     *
     * * `ADMIN` - Admin
     * * `OPERATIONS` - Operations
     * * `SALES` - Sales
     * * `ENROLLMENT_AGENT` - Enrollment Agent
     */
    role: VitableConnect.OrganizationUserRole;
}
