// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Unpaginated ``{"data": [...]}`` list of organization hris providers.
 */
export interface OrganizationHrisProvidersResponse {
    /** The HRIS providers available to the organization. */
    data: VitableConnect.OrganizationHrisProvider[];
}
