// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Envelope for the caller's organization memberships (paginated).
 */
export interface OrganizationsListResponse {
    /** This page of organizations. */
    organizations: VitableConnect.OrganizationMembership[];
    /** Total number of organizations the caller belongs to. */
    total: number;
}
