// This file was auto-generated by Fern from our API Definition.

/**
 * * `ADMIN` - Admin
 * * `OPERATIONS` - Operations
 * * `SALES` - Sales
 * * `ENROLLMENT_AGENT` - Enrollment Agent
 */
export const OrganizationUserRole = {
    Admin: "ADMIN",
    Operations: "OPERATIONS",
    Sales: "SALES",
    EnrollmentAgent: "ENROLLMENT_AGENT",
} as const;
export type OrganizationUserRole = (typeof OrganizationUserRole)[keyof typeof OrganizationUserRole];
