// This file was auto-generated by Fern from our API Definition.

/**
 * * `BROKERAGE` - Brokerage
 * * `TPA` - TPA
 * * `GENERAL_AGENT` - General Agent
 * * `CHANNEL_PARTNER` - Channel Partner
 * * `CONSULTING_FIRM` - Consulting Firm
 * * `API_PLATFORM` - API Platform
 */
export const OrganizationType = {
    Brokerage: "BROKERAGE",
    Tpa: "TPA",
    GeneralAgent: "GENERAL_AGENT",
    ChannelPartner: "CHANNEL_PARTNER",
    ConsultingFirm: "CONSULTING_FIRM",
    ApiPlatform: "API_PLATFORM",
} as const;
export type OrganizationType = (typeof OrganizationType)[keyof typeof OrganizationType];
