// This file was auto-generated by Fern from our API Definition.

export interface OrganizationHrisProvider {
    /** HRIS/payroll provider id, as stored on the connection (e.g. `adp_run`). Filter with this. */
    provider: string;
    /** Display name of that provider (e.g. `ADP Run`). */
    provider_label: string;
}
