// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * One payroll-deduction statement row.
 *
 * Reads a :class:`PayrollDeductionStatementDTO` by attribute: the ``statement_id`` character field renders the
 * prefixed id via ``str()``, and the date/datetime fields emit ISO-8601 strings.
 */
export interface PayrollDeductionStatement {
    /** Prefixed payroll-deduction-statement identifier (`pstmt_<base64-encoded-uuid>`). */
    statement_id: string;
    /** Deduction period start date. */
    period_start: string;
    /** Deduction period end date. */
    period_end: string;
    /** When the statement was generated. */
    run_date: string;
    /** Distinct employees covered by the statement's entries. */
    employee_count: number;
    /** Total payroll deduction for the period, in cents. */
    total_deduction_cents: number;
    /** Download link for the change CSV, or null. */
    csv_file_url: string | null;
    /**
     * Deduction frequency code (e.g. `monthly`).
     *
     * * `weekly` - Weekly
     * * `bi_weekly` - Bi Weekly
     * * `semi_monthly` - Semi Monthly
     * * `monthly` - Monthly
     */
    deduction_frequency: VitableConnect.DeductionFrequency;
    /** Human-readable deduction frequency (e.g. `Monthly`). */
    deduction_frequency_label: string;
}
