// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single payroll integration email resource.
 */
export interface PayrollIntegrationEmailResponse {
    /** The payroll integration email address for the employer. */
    data: VitableConnect.PayrollIntegrationEmail;
}
