// This file was auto-generated by Fern from our API Definition.

/**
 * * `SELF_SETUP` - SELF_SETUP
 * * `NEEDS_HELP` - NEEDS_HELP
 */
export const PayrollAccessMethod = {
    SelfSetup: "SELF_SETUP",
    NeedsHelp: "NEEDS_HELP",
} as const;
export type PayrollAccessMethod = (typeof PayrollAccessMethod)[keyof typeof PayrollAccessMethod];
