// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single payroll access setup status resource.
 */
export interface PayrollAccessSetupStatusResponse {
    /** Current status of the employer's payroll access setup. */
    data: VitableConnect.PayrollAccessSetupStatus;
}
