// This file was auto-generated by Fern from our API Definition.

/**
 * * `Coverage Upcoming` - Coverage Upcoming
 * * `Coverage Effective` - Coverage Effective
 * * `Coverage Ended` - Coverage Ended
 * * `Cancelled` - Cancelled
 */
export const PlanYearEnrollmentPolicyStatus = {
    CoverageUpcoming: "Coverage Upcoming",
    CoverageEffective: "Coverage Effective",
    CoverageEnded: "Coverage Ended",
    Cancelled: "Cancelled",
} as const;
export type PlanYearEnrollmentPolicyStatus =
    (typeof PlanYearEnrollmentPolicyStatus)[keyof typeof PlanYearEnrollmentPolicyStatus];
