// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing plan resources.
 */
export interface PlanListResponse {
    /** This page of plans. */
    data: VitableConnect.Plan[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
