// This file was auto-generated by Fern from our API Definition.

export interface Plan {
    /** Unique identifier for the plan (`plan_*`). */
    id: string;
    /** Human-readable plan name as shown to members. */
    name: string;
}
