// This file was auto-generated by Fern from our API Definition.

/**
 * * `Enrolled` - Enrolled
 * * `Waived` - Waived
 * * `Pending` - Pending
 * * `Expired` - Expired
 */
export const PlanYearEnrollmentElectionStatus = {
    Enrolled: "Enrolled",
    Waived: "Waived",
    Pending: "Pending",
    Expired: "Expired",
} as const;
export type PlanYearEnrollmentElectionStatus =
    (typeof PlanYearEnrollmentElectionStatus)[keyof typeof PlanYearEnrollmentElectionStatus];
