// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

export interface PlanYearEnrollment {
    /** Our id for the person (`mbr_<...>`). Stable across every employer they work for. */
    member_id: string;
    /** Our id for this person's employment with this employer (`empl_<...>`). A person who leaves and is rehired has two. */
    employee_id: string;
    /** Your own reference id for this employee, as you supplied it. Null when you have not set one. */
    employee_external_reference_id: string | null;
    /** The member's first name. */
    member_first_name: string;
    /** The member's last name. */
    member_last_name: string;
    /**
     * Where the member stands: `Enrolled` or `Waived` if they answered, otherwise `Pending` while their enrollment window is open and `Expired` once it has closed.
     *
     * * `Enrolled` - Enrolled
     * * `Waived` - Waived
     * * `Pending` - Pending
     * * `Expired` - Expired
     */
    election_status: VitableConnect.PlanYearEnrollmentElectionStatus;
    /**
     * Where the member's coverage stands: `Coverage Upcoming`, `Coverage Effective`, `Coverage Ended`, or `Cancelled`. Null unless the member enrolled.
     *
     * * `Coverage Upcoming` - Coverage Upcoming
     * * `Coverage Effective` - Coverage Effective
     * * `Coverage Ended` - Coverage Ended
     * * `Cancelled` - Cancelled
     */
    policy_status: VitableConnect.PlanYearEnrollmentPolicyStatus | null;
    /** Dependents covered under this enrollment today. Counts the same dependents `premium_in_cents` is priced for, so a dependent whose termination is dated in the future still counts. */
    dependent_count: number;
    /** The carrier for this enrollment: the individual-market carrier for an ICHRA plan, otherwise the benefit's own. Null when the benefit has no carrier. */
    carrier: string | null;
    /** Chosen plan name, or null when unanswered/waived. */
    plan: string | null;
    /** Chosen coverage tier, or null when unanswered/waived. */
    tier: string | null;
    /** Monthly premium in cents for the chosen plan, dependents included. The plan's own cost, not the employer's share of it. Null when unanswered/waived. */
    premium_in_cents: number | null;
    /** The employer's monthly share of `premium_in_cents`, in cents. Null when unanswered/waived. */
    employer_contribution_in_cents: number | null;
    /** What the employee is deducted monthly, in cents: `premium_in_cents` less `employer_contribution_in_cents`, floored at zero. Null when unanswered/waived. */
    employee_deduction_in_cents: number | null;
}
