// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing plan year enrollment resources.
 */
export interface PlanYearEnrollmentListResponse {
    /** This page of plan year enrollments. */
    data: VitableConnect.PlanYearEnrollment[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
