// This file was auto-generated by Fern from our API Definition.

/**
 * * `en` - English
 * * `es` - Spanish
 * * `zh` - Chinese
 * * `ru` - Russian
 * * `sw` - Swahili
 * * `th` - Thai
 */
export const PreferredLanguage = {
    En: "en",
    Es: "es",
    Zh: "zh",
    Ru: "ru",
    Sw: "sw",
    Th: "th",
} as const;
export type PreferredLanguage = (typeof PreferredLanguage)[keyof typeof PreferredLanguage];
