// This file was auto-generated by Fern from our API Definition.

/**
 * * `EBA` - Eba Mec
 * * `VPC` - Vpc Enhanced
 * * `VPC_CORE` - Vpc Core
 * * `MEC` - Vpc Mec
 * * `MEC2` - Mec2
 * * `MEC_PLUS` - Mec Plus
 * * `MVP` - Mvp
 * * `MVP2` - Mvp2
 * * `MVPSL` - Mvpsl
 * * `MVPSL2` - Mvpsl2
 * * `VD` - Dental
 * * `VV` - Vision
 * * `ICHRA` - Ichra
 * * `ICHRA_PREMIUM_PLUS` - Ichra Premium Plus
 * * `ICHRA_REIMBURSEMENT_ONLY` - Ichra Reimbursement Only
 */
export const ProductCode = {
    Eba: "EBA",
    Vpc: "VPC",
    VpcCore: "VPC_CORE",
    Mec: "MEC",
    Mec2: "MEC2",
    MecPlus: "MEC_PLUS",
    Mvp: "MVP",
    Mvp2: "MVP2",
    Mvpsl: "MVPSL",
    Mvpsl2: "MVPSL2",
    Vd: "VD",
    Vv: "VV",
    Ichra: "ICHRA",
    IchraPremiumPlus: "ICHRA_PREMIUM_PLUS",
    IchraReimbursementOnly: "ICHRA_REIMBURSEMENT_ONLY",
} as const;
export type ProductCode = (typeof ProductCode)[keyof typeof ProductCode];
