// This file was auto-generated by Fern from our API Definition.

/**
 * * `pending` - Pending
 * * `approved` - Approved
 * * `denied` - Denied
 */
export const QualifyingLifeEventStatus = {
    Pending: "pending",
    Approved: "approved",
    Denied: "denied",
} as const;
export type QualifyingLifeEventStatus = (typeof QualifyingLifeEventStatus)[keyof typeof QualifyingLifeEventStatus];
