// This file was auto-generated by Fern from our API Definition.

/**
 * * `lost_job_based_coverage` - lost_job_based_coverage
 * * `aged_off_parent_plan` - aged_off_parent_plan
 * * `lost_medicaid_chip_medicare` - lost_medicaid_chip_medicare
 * * `lost_decertified_individual_plan` - lost_decertified_individual_plan
 * * `married` - married
 * * `divorced` - divorced
 * * `had_baby` - had_baby
 * * `adopted_child` - adopted_child
 * * `foster_care_placement` - foster_care_placement
 * * `death_of_spouse_or_dependent` - death_of_spouse_or_dependent
 * * `court_ordered` - court_ordered
 * * `moved_to_new_coverage_area` - moved_to_new_coverage_area
 * * `moved_to_us` - moved_to_us
 * * `moved_to_or_from_school_housing` - moved_to_or_from_school_housing
 * * `moved_to_or_from_seasonal_work_housing` - moved_to_or_from_seasonal_work_housing
 * * `became_us_citizen` - became_us_citizen
 * * `left_incarceration` - left_incarceration
 * * `gained_tribal_status` - gained_tribal_status
 * * `started_or_ended_americorps_service` - started_or_ended_americorps_service
 * * `new_child` - new_child
 * * `other` - other
 */
export const QualifyingLifeEventType = {
    LostJobBasedCoverage: "lost_job_based_coverage",
    AgedOffParentPlan: "aged_off_parent_plan",
    LostMedicaidChipMedicare: "lost_medicaid_chip_medicare",
    LostDecertifiedIndividualPlan: "lost_decertified_individual_plan",
    Married: "married",
    Divorced: "divorced",
    HadBaby: "had_baby",
    AdoptedChild: "adopted_child",
    FosterCarePlacement: "foster_care_placement",
    DeathOfSpouseOrDependent: "death_of_spouse_or_dependent",
    CourtOrdered: "court_ordered",
    MovedToNewCoverageArea: "moved_to_new_coverage_area",
    MovedToUs: "moved_to_us",
    MovedToOrFromSchoolHousing: "moved_to_or_from_school_housing",
    MovedToOrFromSeasonalWorkHousing: "moved_to_or_from_seasonal_work_housing",
    BecameUsCitizen: "became_us_citizen",
    LeftIncarceration: "left_incarceration",
    GainedTribalStatus: "gained_tribal_status",
    StartedOrEndedAmericorpsService: "started_or_ended_americorps_service",
    NewChild: "new_child",
    Other: "other",
} as const;
export type QualifyingLifeEventType = (typeof QualifyingLifeEventType)[keyof typeof QualifyingLifeEventType];
