// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single reissue enrollment resource.
 */
export interface ReissueEnrollmentResponse {
    /** The reissued enrollment. */
    data: VitableConnect.ReissueEnrollment;
}
