// This file was auto-generated by Fern from our API Definition.

/**
 * * `Spouse` - Spouse
 * * `Child` - Child
 */
export const Relationship = {
    Spouse: "Spouse",
    Child: "Child",
} as const;
export type Relationship = (typeof Relationship)[keyof typeof Relationship];
