// This file was auto-generated by Fern from our API Definition.

/**
 * * `VITABLE_UPDATE` - VITABLE_UPDATE
 * * `EMPLOYER_UPDATE` - EMPLOYER_UPDATE
 */
export const RemainingEmployeeAction = {
    VitableUpdate: "VITABLE_UPDATE",
    EmployerUpdate: "EMPLOYER_UPDATE",
} as const;
export type RemainingEmployeeAction = (typeof RemainingEmployeeAction)[keyof typeof RemainingEmployeeAction];
