// This file was auto-generated by Fern from our API Definition.

/**
 * * `enrollment` - Enrollment
 * * `employee` - Employee
 * * `employer` - Employer
 * * `dependent` - Dependent
 * * `plan_year` - Plan Year
 * * `payroll_deduction` - Payroll Deduction
 */
export const ResourceType = {
    Enrollment: "enrollment",
    Employee: "employee",
    Employer: "employer",
    Dependent: "dependent",
    PlanYear: "plan_year",
    PayrollDeduction: "payroll_deduction",
} as const;
export type ResourceType = (typeof ResourceType)[keyof typeof ResourceType];
