// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single saved member dependent resource.
 */
export interface SavedMemberDependentResponse {
    data: VitableConnect.SavedMemberDependent;
}
