// This file was auto-generated by Fern from our API Definition.

/**
 * Employer filter. Matches the display name or the legal name case-insensitively as a substring, or one of these exactly: the EIN (with or without its dash), the employer id, or the contact email of one of the employer's non-disabled admins.
 */
export type Search = string | null;
