// This file was auto-generated by Fern from our API Definition.

/**
 * * `Male` - Male
 * * `Female` - Female
 * * `Other` - Other
 * * `Unknown` - Unknown
 */
export const SexAtBirth = {
    Male: "Male",
    Female: "Female",
    Other: "Other",
    Unknown: "Unknown",
} as const;
export type SexAtBirth = (typeof SexAtBirth)[keyof typeof SexAtBirth];
