// This file was auto-generated by Fern from our API Definition.

/** Optional. Filter to a single QLE status; omit to return all statuses. */
export const Status = {
    Approved: "approved",
    Denied: "denied",
    Pending: "pending",
} as const;
export type Status = (typeof Status)[keyof typeof Status];
