// This file was auto-generated by Fern from our API Definition.

/**
 * * `AL` - AL
 * * `AK` - AK
 * * `AZ` - AZ
 * * `AR` - AR
 * * `CA` - CA
 * * `CO` - CO
 * * `CT` - CT
 * * `DC` - DC
 * * `DE` - DE
 * * `FL` - FL
 * * `GA` - GA
 * * `HI` - HI
 * * `ID` - ID
 * * `IL` - IL
 * * `IN` - IN
 * * `IA` - IA
 * * `KS` - KS
 * * `KY` - KY
 * * `LA` - LA
 * * `ME` - ME
 * * `MD` - MD
 * * `MA` - MA
 * * `MI` - MI
 * * `MN` - MN
 * * `MS` - MS
 * * `MO` - MO
 * * `MT` - MT
 * * `NE` - NE
 * * `NV` - NV
 * * `NH` - NH
 * * `NJ` - NJ
 * * `NM` - NM
 * * `NY` - NY
 * * `NC` - NC
 * * `ND` - ND
 * * `OH` - OH
 * * `OK` - OK
 * * `OR` - OR
 * * `PA` - PA
 * * `RI` - RI
 * * `SC` - SC
 * * `SD` - SD
 * * `TN` - TN
 * * `TX` - TX
 * * `UT` - UT
 * * `VT` - VT
 * * `VA` - VA
 * * `WA` - WA
 * * `WI` - WI
 * * `WV` - WV
 * * `WY` - WY
 * * `PR` - PR
 * * `GU` - GU
 * * `AS` - AS
 * * `VI` - VI
 * * `MP` - MP
 * * `MH` - MH
 * * `PW` - PW
 * * `FM` - FM
 * * `AE` - AE
 * * `AA` - AA
 * * `AP` - AP
 */
export const State = {
    Al: "AL",
    Ak: "AK",
    Az: "AZ",
    Ar: "AR",
    Ca: "CA",
    Co: "CO",
    Ct: "CT",
    Dc: "DC",
    De: "DE",
    Fl: "FL",
    Ga: "GA",
    Hi: "HI",
    Id: "ID",
    Il: "IL",
    In: "IN",
    Ia: "IA",
    Ks: "KS",
    Ky: "KY",
    La: "LA",
    Me: "ME",
    Md: "MD",
    Ma: "MA",
    Mi: "MI",
    Mn: "MN",
    Ms: "MS",
    Mo: "MO",
    Mt: "MT",
    Ne: "NE",
    Nv: "NV",
    Nh: "NH",
    Nj: "NJ",
    Nm: "NM",
    Ny: "NY",
    Nc: "NC",
    Nd: "ND",
    Oh: "OH",
    Ok: "OK",
    Or: "OR",
    Pa: "PA",
    Ri: "RI",
    Sc: "SC",
    Sd: "SD",
    Tn: "TN",
    Tx: "TX",
    Ut: "UT",
    Vt: "VT",
    Va: "VA",
    Wa: "WA",
    Wi: "WI",
    Wv: "WV",
    Wy: "WY",
    Pr: "PR",
    Gu: "GU",
    As: "AS",
    Vi: "VI",
    Mp: "MP",
    Mh: "MH",
    Pw: "PW",
    Fm: "FM",
    Ae: "AE",
    Aa: "AA",
    Ap: "AP",
} as const;
export type State = (typeof State)[keyof typeof State];
