// This file was auto-generated by Fern from our API Definition.

/**
 * * `Unknown` - Unknown
 * * `Pre-tax` - Pre Tax
 * * `Post-tax` - Post Tax
 */
export const TaxClassification = {
    Unknown: "Unknown",
    PreTax: "Pre-tax",
    PostTax: "Post-tax",
} as const;
export type TaxClassification = (typeof TaxClassification)[keyof typeof TaxClassification];
