// This file was auto-generated by Fern from our API Definition.

/**
 * * `END_OF_N_MONTHS` - End Of N Months
 * * `END_OF_PLAN_YEAR` - End Of Plan Year
 */
export const TerminationRule = {
    EndOfNMonths: "END_OF_N_MONTHS",
    EndOfPlanYear: "END_OF_PLAN_YEAR",
} as const;
export type TerminationRule = (typeof TerminationRule)[keyof typeof TerminationRule];
