// This file was auto-generated by Fern from our API Definition.

/**
 * * `FIRST_OF_FOLLOWING_MONTH` - First Of Following Month
 * * `THIRTY_DAYS` - Thirty Days
 * * `SIXTY_DAYS` - Sixty Days
 */
export const WaitingPeriod = {
    FirstOfFollowingMonth: "FIRST_OF_FOLLOWING_MONTH",
    ThirtyDays: "THIRTY_DAYS",
    SixtyDays: "SIXTY_DAYS",
} as const;
export type WaitingPeriod = (typeof WaitingPeriod)[keyof typeof WaitingPeriod];
