// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Response containing a single webhook event resource.
 */
export interface WebhookEventResponse {
    /** The webhook event. */
    data: VitableConnect.WebhookEvent;
}
