// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../index.js";

/**
 * Paginated list response containing webhook event resources.
 */
export interface WebhookEventListResponse {
    /** This page of webhook events. */
    data: VitableConnect.WebhookEvent[];
    /** Page metadata. Request the next page by incrementing `page`. */
    pagination: VitableConnect.Pagination;
}
