// This file was auto-generated by Fern from our API Definition.

export interface WebhookEvent {
    /** Prefixed unique identifier for this webhook event (e.g., `wevt_...`). */
    id: string;
    /** The organization this event belongs to. */
    organization_id: string;
    /** The event type, formatted as `{resource}.{action}` (e.g., `enrollment.accepted`). */
    event_name: string;
    /** The type of resource affected (e.g., `enrollment`, `employee`). */
    resource_type: string;
    /** Prefixed ID of the affected resource. Use this to fetch the current state from the API. */
    resource_id: string;
    /** When the event occurred, in UTC. */
    created_at: string;
}
