// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../../../src/api/index";
import { VitableConnectClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("SyncClient", () => {
    test("submit (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "EMP-001",
                    first_name: "Jane",
                    last_name: "Doe",
                    date_of_birth: "1990-05-15",
                    phone: "4155550100",
                    plan_id: "pln_abc123def456",
                    address: {
                        address_line_1: "123 Main Street",
                        address_line_2: "Apt 4B",
                        city: "San Francisco",
                        state: "CA",
                        zipcode: "94102",
                    },
                    email: "jane.doe@acme.com",
                },
            ],
        };
        const rawResponseBody = {
            data: {
                request_id: "grpmsr_abc123def456",
                group_id: "grp_abc123def456",
                accepted_at: "2026-01-15T10:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/groups/grp_abc123def456/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.groups.members.sync.submit({
            group_id: "grp_abc123def456",
            members: [
                {
                    reference_id: "EMP-001",
                    first_name: "Jane",
                    last_name: "Doe",
                    date_of_birth: "1990-05-15",
                    phone: "4155550100",
                    plan_id: "pln_abc123def456",
                    address: {
                        address_line_1: "123 Main Street",
                        address_line_2: "Apt 4B",
                        city: "San Francisco",
                        state: "CA",
                        zipcode: "94102",
                    },
                    email: "jane.doe@acme.com",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("submit (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("submit (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("submit (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("submit (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("submit (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("submit (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.UnprocessableEntityError);
    });

    test("submit (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("submit (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("submit (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            members: [
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
                {
                    reference_id: "x",
                    first_name: "first_name",
                    last_name: "last_name",
                    date_of_birth: "2023-01-15",
                    plan_id: "x",
                    address: { address_line_1: "x", city: "x", state: "xy", zipcode: "x" },
                },
            ],
        };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups/group_id/members/sync")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.submit({
                group_id: "group_id",
                members: [
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                    {
                        reference_id: "x",
                        first_name: "first_name",
                        last_name: "last_name",
                        date_of_birth: "2023-01-15",
                        plan_id: "x",
                        address: {
                            address_line_1: "x",
                            city: "x",
                            state: "xy",
                            zipcode: "x",
                        },
                    },
                ],
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                request_id: "grpmsr_abc123def456",
                group_id: "grp_abc123def456",
                accepted_at: "2026-01-15T10:30:00Z",
                completed_at: "2026-01-15T10:30:42Z",
                results: {
                    added_group_member_ids: ["grpmbr_abc123def456"],
                    removed_group_member_ids: ["grpmbr_xyz789ghi012"],
                    failures: [{ reference_id: "EMP-002", operation: "add", reason: "Invalid plan_id" }],
                },
            },
        };

        server
            .mockEndpoint()
            .get("/v1/groups/grp_abc123def456/members/sync/request_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.groups.members.sync.get({
            group_id: "grp_abc123def456",
            request_id: "request_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id/members/sync/request_id")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.members.sync.get({
                group_id: "group_id",
                request_id: "request_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
