// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { SyncClient } from "../resources/sync/client/Client.js";

export declare namespace MembersClient {
    export type Options = BaseClientOptions;
}

export class MembersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MembersClient.Options>;
    protected _sync: SyncClient | undefined;

    constructor(options: MembersClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get sync(): SyncClient {
        return (this._sync ??= new SyncClient(this._options));
    }
}
