// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../src/api/index";
import { VitableConnectClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthClient", () => {
    test("issue_access_token (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            access_token: "vit_at_abc123def456...",
            token_type: "Bearer",
            expires_in: 910,
            bound_entity: { id: "empr_SGVsbG8gV29ybGQ", type: "employer" },
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.issueAccessToken({
            grant_type: "client_credentials",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("issue_access_token (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            grant_type: "client_credentials",
            bound_entity: { id: "empr_SGVsbG8gV29ybGQ", type: "employer" },
        };
        const rawResponseBody = {
            access_token: "vit_at_abc123def456...",
            token_type: "Bearer",
            expires_in: 910,
            bound_entity: { id: "empr_SGVsbG8gV29ybGQ", type: "employer" },
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.issueAccessToken({
            grant_type: "client_credentials",
            bound_entity: {
                id: "empr_SGVsbG8gV29ybGQ",
                type: "employer",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("issue_access_token (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("issue_access_token (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("issue_access_token (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("issue_access_token (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("issue_access_token (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("issue_access_token (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("issue_access_token (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("issue_access_token (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { grant_type: "client_credentials" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/auth/access-tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.issueAccessToken({
                grant_type: "client_credentials",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
