// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../src/api/index";
import { VitableConnectClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EmployeesClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "empl_abc123",
                member_id: "mbr_xyz789",
                employer_id: "employer_id",
                reference_id: "partner-ee-001",
                employer_name: "employer_name",
                first_name: "John",
                last_name: "Doe",
                email: "john.doe@example.com",
                date_of_birth: "1985-06-15",
                phone: "4155551234",
                employee_class: "Full Time",
                status: "active",
                start_date: "2023-01-15",
                classification_effective_date: "2023-03-01",
                compensation_type: "Salary",
                compensation_type_effective_date: "2023-03-01",
                address: {
                    address_line_1: "456 Oak Avenue",
                    address_line_2: "Apt 2B",
                    city: "San Francisco",
                    state: "CA",
                    zipcode: "94102",
                },
                deductions: [
                    {
                        deduction_amount_in_cents: 1,
                        tax_classification: "Unknown",
                        frequency: "weekly",
                        benefit_name: "benefit_name",
                        period_start_date: "2023-01-15",
                        period_end_date: "2023-01-15",
                    },
                ],
                created_at: "2023-01-15T09:00:00Z",
                updated_at: "2024-06-01T14:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/employees/empl_abc123def456")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.employees.get({
            employee_id: "empl_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.get({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            employee_class: "Full Time",
            start_date: "2023-01-15",
            compensation_type: "Salary",
            effective_date: "2023-03-01",
        };
        const rawResponseBody = {
            data: {
                id: "id",
                member_id: "member_id",
                employer_id: "employer_id",
                reference_id: "reference_id",
                employer_name: "employer_name",
                first_name: "first_name",
                last_name: "last_name",
                suffix: "suffix",
                email: "email",
                date_of_birth: "2023-01-15",
                gender: "gender",
                phone: "phone",
                employee_class: "Full Time",
                status: "active",
                start_date: "2023-01-15",
                classification_effective_date: "2023-01-15",
                compensation_type: "Salary",
                compensation_type_effective_date: "2023-01-15",
                termination_date: "2023-01-15",
                address: {
                    address_line_1: "address_line_1",
                    address_line_2: "address_line_2",
                    city: "city",
                    state: "state",
                    zipcode: "zipcode",
                },
                deductions: [
                    {
                        deduction_amount_in_cents: 1,
                        tax_classification: "Unknown",
                        frequency: "weekly",
                        benefit_name: "benefit_name",
                        period_start_date: "2023-01-15",
                        period_end_date: "2023-01-15",
                    },
                ],
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/empl_abc123def456")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.employees.update({
            employee_id: "empl_abc123def456",
            employee_class: "Full Time",
            start_date: "2023-01-15",
            compensation_type: "Salary",
            effective_date: "2023-03-01",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("update (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { effective_date: "2023-01-15" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/employees/employee_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.update({
                employee_id: "employee_id",
                effective_date: "2023-01-15",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_enrollments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "enrl_abc123def456",
                    employee_id: "empl_xyz789ghi012",
                    employer_id: "empr_def456ghi789",
                    benefit: { id: "bprd_medical456", name: "MEC Plus", product_code: "MEC_PLUS", category: "Medical" },
                    status: "enrolled",
                    coverage_start: "2026-04-01",
                    coverage_end: "2027-03-31",
                    employee_deduction_in_cents: 5000,
                    employer_contribution_in_cents: 25000,
                    answered_at: "2026-01-20T14:30:00Z",
                    created_at: "2026-01-15T10:30:00Z",
                    updated_at: "2026-01-15T10:30:00Z",
                },
            ],
            pagination: { page: 1, limit: 20, total: 1, total_pages: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/employees/empl_abc123def456/enrollments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.employees.listEnrollments({
            employee_id: "empl_abc123def456",
            limit: 20,
            page: 1,
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_enrollments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_enrollments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_enrollments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_enrollments (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_enrollments (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_enrollments (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_enrollments (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_enrollments (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/employees/employee_id/enrollments")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.employees.listEnrollments({
                employee_id: "employee_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
