// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../src/api/index";
import { VitableConnectClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GroupsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "grp_abc123def456",
                    organization_id: "org_abc123def456",
                    name: "Tier 1",
                    external_reference_id: "mol_seg_001",
                    created_at: "2026-01-15T10:30:00Z",
                    updated_at: "2026-01-15T10:30:00Z",
                },
            ],
            pagination: { page: 1, limit: 20, total: 1, total_pages: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/groups")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.groups.list({
            limit: 20,
            page: 1,
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/groups").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.groups.list();
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Tier 1", external_reference_id: "mol_seg_001" };
        const rawResponseBody = {
            data: {
                id: "grp_abc123def456",
                organization_id: "org_abc123def456",
                name: "Tier 1",
                external_reference_id: "mol_seg_001",
                created_at: "2026-01-15T10:30:00Z",
                updated_at: "2026-01-15T10:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.groups.create({
            name: "Tier 1",
            external_reference_id: "mol_seg_001",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.UnprocessableEntityError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("create (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x", external_reference_id: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/groups")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.create({
                name: "x",
                external_reference_id: "x",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "grp_abc123def456",
                organization_id: "org_abc123def456",
                name: "Tier 1",
                external_reference_id: "mol_seg_001",
                created_at: "2026-01-15T10:30:00Z",
                updated_at: "2026-01-15T10:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/groups/grp_abc123def456")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.groups.get({
            group_id: "grp_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/groups/group_id")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.get({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Tier 1 (renamed)", external_reference_id: "mol_seg_001_v2" };
        const rawResponseBody = {
            data: {
                id: "grp_abc123def456",
                organization_id: "org_abc123def456",
                name: "Tier 1 (renamed)",
                external_reference_id: "mol_seg_001_v2",
                created_at: "2026-01-15T10:30:00Z",
                updated_at: "2026-01-16T09:12:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/grp_abc123def456")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.groups.update({
            group_id: "grp_abc123def456",
            name: "Tier 1 (renamed)",
            external_reference_id: "mol_seg_001_v2",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("update (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.UnprocessableEntityError);
    });

    test("update (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("update (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("update (10)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .patch("/v1/groups/group_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.groups.update({
                group_id: "group_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
