// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../src/api/index";
import { VitableConnectClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MembersClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "mbr_abc123def456",
                first_name: "Jane",
                last_name: "Doe",
                email: "jane.doe@example.com",
                phone: "4155550100",
                address: {
                    address_line_1: "123 Main Street",
                    address_line_2: "Apt 4B",
                    city: "San Francisco",
                    state: "CA",
                    zipcode: "94102",
                },
                name: "Jane Doe",
                date_of_birth: "1990-04-12",
                age: 36,
                sex_at_birth: "Female",
                gender: "Female",
                preferred_language: "en",
                tobacco_status: false,
                marital_status: "Single",
                status: "onboarded",
            },
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.get({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.get({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_dependents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    member_id: "member_id",
                    primary_member_id: "primary_member_id",
                    first_name: "first_name",
                    last_name: "last_name",
                    relationship: "Child",
                    date_of_birth: "2015-06-01",
                    age: 11,
                    sex_at_birth: "Male",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456/dependents")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.listDependents({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_dependents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_dependents (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_dependents (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_dependents (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_dependents (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_dependents (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_dependents (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_dependents (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/dependents")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listDependents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_employments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "empl_abc123def456",
                    member_id: "mbr_abc123def456",
                    employer_id: "employer_id",
                    reference_id: "reference_id",
                    employer_name: "Acme Corp",
                    first_name: "Jane",
                    last_name: "Doe",
                    suffix: "suffix",
                    email: "email",
                    date_of_birth: "2023-01-15",
                    gender: "gender",
                    phone: "phone",
                    employee_class: "Full Time",
                    status: "active",
                    start_date: "2024-01-15",
                    classification_effective_date: "2023-01-15",
                    compensation_type: "Salary",
                    compensation_type_effective_date: "2023-01-15",
                    address: { address_line_1: "address_line_1", city: "city", state: "state", zipcode: "zipcode" },
                    deductions: [
                        {
                            deduction_amount_in_cents: 1,
                            tax_classification: "Unknown",
                            frequency: "weekly",
                            benefit_name: "benefit_name",
                            period_start_date: "2023-01-15",
                            period_end_date: "2023-01-15",
                        },
                    ],
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456/employments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.listEmployments({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_employments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_employments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_employments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_employments (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_employments (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_employments (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_employments (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_employments (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/employments")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEmployments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_enrollments (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "enrl_AAAAAAAAAAAAAAAAAAAAAQ",
                    employer_id: "empr_AAAAAAAAAAAAAAAAAAAAAQ",
                    benefit_plan_year_id: "plyr_AAAAAAAAAAAAAAAAAAAAAQ",
                    benefit_type: "Medical",
                    product_code: "MEC_PLUS",
                    requires_qle_for_reissue: false,
                    product_name: "MEC Plus",
                    employer_name: "Acme Corp",
                    carrier_name: "Vitable",
                    plan_name: "MEC Plus Standard",
                    tier_name: "Employee Only",
                    employee_deduction_in_cents: 5000,
                    employer_contribution_in_cents: 25000,
                    premium_in_cents: 30000,
                    coverage_start: "2026-04-01",
                    coverage_end: "2026-08-31",
                    plan_year_coverage_end: "2026-12-31",
                    issued_date: "2026-03-04",
                    enrollment_window_start: "2026-03-04",
                    enrollment_window_end: "2026-03-31",
                    election_status: "Enrolled",
                    policy_status: "Coverage Effective",
                    in_last_month_of_coverage: true,
                    is_within_enrollment_window: false,
                },
                {
                    id: "enrl_AAAAAAAAAAAAAAAAAAAAAg",
                    employer_id: "empr_AAAAAAAAAAAAAAAAAAAAAg",
                    benefit_plan_year_id: "plyr_AAAAAAAAAAAAAAAAAAAAAg",
                    benefit_type: "Dental",
                    product_code: "VD",
                    requires_qle_for_reissue: true,
                    product_name: "Vitable Dental",
                    employer_name: "Acme Corp",
                    carrier_name: "Vitable",
                    plan_year_coverage_end: "2026-12-31",
                    issued_date: "2026-03-04",
                    enrollment_window_start: "2026-03-04",
                    enrollment_window_end: "2026-03-31",
                    election_status: "Waived",
                    in_last_month_of_coverage: false,
                    is_within_enrollment_window: false,
                },
                {
                    id: "enrl_AAAAAAAAAAAAAAAAAAAAAw",
                    employer_id: "empr_AAAAAAAAAAAAAAAAAAAAAQ",
                    benefit_plan_year_id: "plyr_AAAAAAAAAAAAAAAAAAAAAQ",
                    benefit_type: "Dental",
                    product_code: "VD",
                    requires_qle_for_reissue: true,
                    product_name: "Vitable Dental",
                    employer_name: "Acme Corp",
                    carrier_name: "Vitable",
                    plan_name: "Vitable Dental Standard",
                    tier_name: "Employee Only",
                    employee_deduction_in_cents: 1200,
                    employer_contribution_in_cents: 800,
                    premium_in_cents: 2000,
                    cancelled_date: "2026-03-15",
                    plan_year_coverage_end: "2026-12-31",
                    issued_date: "2026-03-04",
                    enrollment_window_start: "2026-03-04",
                    enrollment_window_end: "2026-03-31",
                    election_status: "Enrolled",
                    policy_status: "Cancelled",
                    in_last_month_of_coverage: false,
                    is_within_enrollment_window: false,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456/enrollments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.listEnrollments({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_enrollments (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_enrollments (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_enrollments (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_enrollments (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_enrollments (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_enrollments (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_enrollments (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_enrollments (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/enrollments")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listEnrollments({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("get_household (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    member_id: "mbr_abc123def456",
                    first_name: "first_name",
                    last_name: "last_name",
                    member_type: "Account Holder",
                    date_of_birth: "1990-04-12",
                    household_admin_in: true,
                },
                {
                    member_id: "mbr_def456abc789",
                    first_name: "first_name",
                    last_name: "last_name",
                    relationship: "Spouse",
                    member_type: "Account Holder",
                    date_of_birth: "1989-02-03",
                    household_admin_in: false,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456/household")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.getHousehold({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_household (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("get_household (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("get_household (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("get_household (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("get_household (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("get_household (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("get_household (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("get_household (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/household")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.getHousehold({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_id_cards (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    card_type: "medical",
                    group_id: "GRP-000123",
                    group_member_id: "GM-000456",
                    member_name: "Jane Doe",
                    employer_name: "Acme Inc.",
                    plan_name: "MEC Plus Standard",
                    benefit_code: "MEC_PLUS",
                    network: {
                        id: "5f1c1f9e-6d4a-4b21-9f77-2d4c8f0a1b33",
                        name: "First Health",
                        logo: "https://assets.vitablehealth.com/networks/first-health.png",
                        address: {
                            address_line_1: "123 Main Street",
                            city: "San Francisco",
                            state: "CA",
                            zipcode: "94102",
                        },
                        edi: "87726",
                        website: "https://firsthealth.example.com",
                        phone: "(800) 555-0100",
                        member_website: "https://firsthealth.example.com/members",
                        member_phone: "(800) 555-0101",
                        provider_website: "https://firsthealth.example.com/providers",
                        provider_phone: "(800) 555-0102",
                    },
                    claims_payer_display_name: "Vitable Health",
                    carrier_phone: "(800) 555-0100",
                    carrier_website: "https://vitablehealth.com",
                    plan_disclaimer: "This plan is not major medical insurance.",
                    general_disclaimer: "Possession of this card does not guarantee coverage.",
                    nsa_table: [
                        ["Primary care", "$0"],
                        ["Specialist", "$40"],
                    ],
                },
                {
                    card_type: "rx",
                    group_id: "TEST125",
                    group_member_id: "RX-000789",
                    member_name: "Jane Doe",
                    employer_name: "Acme Inc.",
                    nsa_table: [["nsa_table"]],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v1/members/mbr_abc123def456/id-cards")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.members.listIdCards({
            member_id: "mbr_abc123def456",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("list_id_cards (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_id_cards (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_id_cards (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_id_cards (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_id_cards (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_id_cards (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_id_cards (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_id_cards (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/id-cards")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listIdCards({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list_qualifying_life_events (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "qle_AAAAAAAAAAAAAAAAAAAAAQ",
                    event_type: "other",
                    event_type_label: "Other",
                    other_event: "Relocation",
                    status: "approved",
                    submitted_at: "2026-07-01T14:30:00Z",
                },
            ],
            pagination: { page: 1, limit: 20, total: 1, total_pages: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/members/mbr_abc123def456/qualifying-life-events")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.members.listQualifyingLifeEvents({
            member_id: "mbr_abc123def456",
            limit: 20,
            page: 1,
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list_qualifying_life_events (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list_qualifying_life_events (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list_qualifying_life_events (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list_qualifying_life_events (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list_qualifying_life_events (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list_qualifying_life_events (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list_qualifying_life_events (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list_qualifying_life_events (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .get("/v1/members/member_id/qualifying-life-events")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.members.listQualifyingLifeEvents({
                member_id: "member_id",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "mbr_abc123def456",
                    first_name: "Jane",
                    last_name: "Doe",
                    email: "jane.doe@example.com",
                    phone: "4155550100",
                    address: {
                        address_line_1: "123 Main Street",
                        address_line_2: "Apt 4B",
                        city: "San Francisco",
                        state: "CA",
                        zipcode: "94102",
                    },
                },
            ],
            pagination: { page: 1, limit: 20, total: 1, total_pages: 1 },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v2/members")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = rawResponseBody;
        const page = await client.members.list({
            limit: 20,
            page: 1,
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v2/members").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.members.list();
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
