// This file was auto-generated by Fern from our API Definition.

import * as VitableConnect from "../../src/api/index";
import { VitableConnectClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrganizationsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            organizations: [
                {
                    id: "org_abc123def456",
                    name: "Acme Brokerage",
                    type: "BROKERAGE",
                    idp_org_id: "org_01J0WORKOS",
                    idp_provider: "workos",
                    super_in: false,
                },
            ],
            total: 1,
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.organizations.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("list (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("list (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("list (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server.mockEndpoint().get("/v1/organizations").respondWith().statusCode(502).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.organizations.list();
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "Acme Brokerage", type: "BROKERAGE" };
        const rawResponseBody = {
            id: "org_abc123def456",
            name: "Acme Brokerage",
            type: "BROKERAGE",
            idp_org_id: "org_01J0WORKOS",
            idp_provider: "workos",
            super_in: false,
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.create({
            name: "Acme Brokerage",
            type: "BROKERAGE",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.ConflictError);
    });

    test("create (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.TooManyRequestsError);
    });

    test("create (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.InternalServerError);
    });

    test("create (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new VitableConnectClient({
            maxRetries: 0,
            apiKeyAuth: { apiKey: "test" },
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {
            timestamp: "2024-01-15T09:30:00Z",
            message: "message",
            error: "error",
            trace_id: "trace_id",
        };

        server
            .mockEndpoint()
            .post("/v1/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.create({
                name: "x",
            });
        }).rejects.toThrow(VitableConnect.BadGatewayError);
    });
});
