// This file was auto-generated by Fern from our API Definition.

export const VitableConnectEnvironment = {
    Production: "https://api.vitablehealth.com",
    Uat: "https://api.uat.vitablehealth.com",
} as const;

export type VitableConnectEnvironment =
    | typeof VitableConnectEnvironment.Production
    | typeof VitableConnectEnvironment.Uat;
