// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         event_id: "event_id"
 *     }
 */
export interface GetWebhookEventsRequest {
    event_id: VitableConnect.EventId;
}
