// This file was auto-generated by Fern from our API Definition.

import type * as VitableConnect from "../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         page: 1
 *     }
 */
export interface ListWebhookEventsRequest {
    created_after?: VitableConnect.CreatedAfter;
    created_before?: VitableConnect.CreatedBefore;
    /**
     * * `enrollment.accepted` - Enrollment Accepted
     * * `enrollment.terminated` - Enrollment Terminated
     * * `enrollment.termination_rescheduled` - Enrollment Termination Rescheduled
     * * `enrollment.elected` - Enrollment Elected
     * * `enrollment.granted` - Enrollment Granted
     * * `enrollment.waived` - Enrollment Waived
     * * `enrollment.started` - Enrollment Started
     * * `employee.eligibility_granted` - Employee Eligibility Granted
     * * `employee.eligibility_terminated` - Employee Eligibility Terminated
     * * `employee.deactivated` - Employee Deactivated
     * * `employee.deduction_created` - Employee Deduction Created
     */
    event_name?: VitableConnect.EventName;
    limit?: VitableConnect.Limit;
    page?: VitableConnect.Page;
    resource_id?: VitableConnect.ResourceId;
    /**
     * * `enrollment` - Enrollment
     * * `employee` - Employee
     * * `employer` - Employer
     * * `dependent` - Dependent
     * * `plan_year` - Plan Year
     * * `payroll_deduction` - Payroll Deduction
     */
    resource_type?: VitableConnect.ResourceType;
}
